### ISSUE TITLE
Error in building/Compiling traccar from source code

### ISSUE THREAD

**Issue by manee1982** [tananaev/traccar#1036]
First of all, traccar is really great open source tracking application.
Thank you really for this effort.

1- i start download traccar-web from latest code in the github.com repository.
2- i downloaded the Eclipse Indego 7.3, and i installed google plugin (GWT).
3- I followed the steps mentioned to start building from source code.
i use Ubtuntu 14.04, i configure all things requred to start buld from source.

Now when i run it as web application in eclipse i get this error in the browser
Error - Remote procedure call error.
## Compilation result is:
```
Runing CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.7, -bindAddress, 127.0.0.1, -launcherDir, /home/manee/GPSTracking/traccar-web/war, -logLevel, INFO, org.traccar.web.Traccar]
Super Dev Mode starting up
   workDir: /tmp/gwt-codeserver-7872869741663991762.tmp
   Loading Java files in org.traccar.web.Traccar.
   Ignored 1 unit with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   Module setup completed in 16708 ms

The code server is ready at http://127.0.0.1:9876/
Code server started in 17000 ms
waited 8492 ms for code server to finish
GET /recompile/traccar
   Job org.traccar.web.Traccar_1_0
      starting job: org.traccar.web.Traccar_1_0
      binding: gxt.user.agent=gecko1_9
      binding: user.agent=gecko1_8
      binding: user.agent.os=linux
      Compiling module org.traccar.web.Traccar
         Ignored 1 unit with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
         Computing all possible rebind results for 'com.sencha.gxt.theme.blue.client.window.BlueWindowAppearance.BlueWindowDivFrameResources'
            Rebinding com.sencha.gxt.theme.blue.client.window.BlueWindowAppearance.BlueWindowDivFrameResources
               Invoking generator com.google.gwt.resources.rebind.context.InlineClientBundleGenerator
                  Preparing method background
                     [WARN] Resource 'com/sencha/gxt/core/public/clear.gif' was located via ClassLoader. As a result changes in that resource will not be reflected in per-file recompiles. It should be registered via  <source /> or <resource /> entry in your .gwt.xml. In a future version of GWT, we will remove this fallback and your application will stop compiling
         Computing all possible rebind results for 'com.sencha.gxt.theme.blue.client.button.BlueButtonGroupAppearance.BlueButtonGroupTableFrameResources'
            Rebinding com.sencha.gxt.theme.blue.client.button.BlueButtonGroupAppearance.BlueButtonGroupTableFrameResources
               Invoking generator com.google.gwt.resources.rebind.context.InlineClientBundleGenerator
                  Preparing method background
                     [WARN] Resource 'com/sencha/gxt/core/public/clear.gif' was located via ClassLoader. As a result changes in that resource will not be reflected in per-file recompiles. It should be registered via  <source /> or <resource /> entry in your .gwt.xml. In a future version of GWT, we will remove this fallback and your application will stop compiling
         Computing all possible rebind results for 'com.sencha.gxt.theme.base.client.field.ErrorTipDefaultAppearance.ErrorTipFrameResources'
            Rebinding com.sencha.gxt.theme.base.client.field.ErrorTipDefaultAppearance.ErrorTipFrameResources
               Invoking generator com.google.gwt.resources.rebind.context.InlineClientBundleGenerator
                  Preparing method background
                     [WARN] Resource 'com/sencha/gxt/core/public/clear.gif' was located via ClassLoader. As a result changes in that resource will not be reflected in per-file recompiles. It should be registered via  <source /> or <resource /> entry in your .gwt.xml. In a future version of GWT, we will remove this fallback and your application will stop compiling
         Unification traversed 41051 fields and methods and 4030 types. 3974 are considered part of the current module and 3974 had all of their fields and methods traversed.
         Compiling 1 permutation
            Compiling permutation 0...
            Linking per-type JS with 3958 new types.
               prelink JS size = 7688395
               prelink sourcemap = 7688395 bytes and 185603 lines
               postlink JS size = 7350174
               postlink sourcemap = 7350174 bytes and 178374 lines
            Source Maps Enabled
         Compile of permutations succeeded
         Compilation succeeded -- 35.482s
      Linking into /tmp/gwt-codeserver-7872869741663991762.tmp/org.traccar.web.Traccar/compile-2/war/traccar; Writing extras to /tmp/gwt-codeserver-7872869741663991762.tmp/org.traccar.web.Traccar/compile-2/extras/traccar
         Link succeeded
         Linking succeeded -- 2.137s
      37.933s total -- Compile completed
Jan 20, 2015 9:18:22 PM org.hibernate.annotations.common.Version <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {4.0.1.Final}
Jan 20, 2015 9:18:22 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {4.1.10.Final}
Jan 20, 2015 9:18:22 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Jan 20, 2015 9:18:22 PM org.hibernate.cfg.Environment buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
Jan 20, 2015 9:18:23 PM org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000402: Using Hibernate built-in connection pool (not for production use!)
Jan 20, 2015 9:18:23 PM org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000115: Hibernate connection pool size: 20
Jan 20, 2015 9:18:23 PM org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000006: Autocommit mode: true
Jan 20, 2015 9:18:23 PM org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000401: using driver [org.h2.Driver] at URL [jdbc:h2:/home/user/Documents/traccar-web/database]
Jan 20, 2015 9:18:23 PM org.hibernate.service.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000046: Connection properties: {user=sa, password=***_, autocommit=true, release_mode=auto}
[WARN] Server class 'com.ibm.icu.text.Collator' could not be found in the web app, but was found on the system classpath
   [WARN] Adding classpath entry 'file:/usr/local/gwt-2.7.0/gwt-dev.jar' to the web app classpath for this session
   For additional info see: file:/usr/local/gwt-2.7.0/doc/helpInfo/webAppClassPath.html
Jan 20, 2015 9:18:25 PM org.hibernate.engine.jdbc.internal.JdbcServicesImpl configure
WARN: HHH000342: Could not obtain connection to query metadata : Error while creating file "/home/user" [90062-171]
Starting Jetty on port 8888
   [WARN] unavailable
javax.persistence.PersistenceException: [PersistenceUnit: debug] Unable to build EntityManagerFactory
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
    at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:57)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
    at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:66)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:534)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:417)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:659)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:68)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
    at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
    at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:77)
    at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2276)
    at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2272)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1741)
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
    ... 34 more
   [WARN] 
javax.servlet.ServletException: dataService
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:555)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:417)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:659)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:68)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:744)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: debug] Unable to build EntityManagerFactory
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
    at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:57)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
    at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:66)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:534)
    ... 26 more
Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
    at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
    at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:77)
    at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2276)
    at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2272)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1741)
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
    ... 34 more
   [WARN] /traccar/dataService
javax.persistence.PersistenceException: [PersistenceUnit: debug] Unable to build EntityManagerFactory
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:915)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
    at org.hibernate.ejb.HibernatePersistence.createEntityManagerFactory(HibernatePersistence.java:57)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
    at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:66)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:534)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:417)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:659)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:68)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
    at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
    at org.hibernate.service.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:75)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:159)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:131)
    at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:77)
    at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2276)
    at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2272)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1741)
    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
    ... 34 more
[ERROR] 500 - POST /traccar/dataService (127.0.0.1) 9800 bytes
   Request headers
      Host: 127.0.0.1:8888
      User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/*;q=0.8
      Accept-Language: en-US,en;q=0.5
      Accept-Encoding: gzip, deflate
      Content-Type: text/x-gwt-rpc; charset=utf-8
      X-GWT-Permutation: F9F028F7F2E09EF605F8F320A7708F83
      X-GWT-Module-Base: http://127.0.0.1:8888/traccar/
      Referer: http://127.0.0.1:8888/traccar.html
      Content-Length: 210
      Connection: keep-alive
      Pragma: no-cache
      Cache-Control: no-cache
   Response headers
      Content-Type: text/html;charset=ISO-8859-1
      Cache-Control: must-revalidate,no-cache,no-store
      Content-Length: 9800
```
I need to know where is missed up, Thank you again.

**Comment by manee1982** [comment]
Sorry for inconvinience.
------------------------------
I descovered that i have stupid mistake in my persistence.xml file. Now it's work fine with this configurations:

![screenshot from 2015-01-20 22 35 21](https://cloud.githubusercontent.com/assets/3728338/5824351/18bfb4b0-a0f5-11e4-97df-e84e70d18d48.png)

<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
  <persistence-unit name="release">
    <non-jta-data-source>java:/DefaultDS</non-jta-data-source>
    <properties>
      <property name="hibernate.show_sql" value="false"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
  </persistence-unit>
  <persistence-unit name="debug">
    <properties>
      <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver"/>
      <property name="hibernate.connection.url" value="jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true"/>
      <property name="hibernate.connection.username" value="UserOfDatabase"/>
      <property name="hibernate.connection.password" value="Passwd"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
  </persistence-unit>
</persistence>

**Comment by manee1982** [comment]
another issue
-----------------
When i run step number 6. Run package script (./package.sh).
it says: 
mv: cannot stat ‘war/WEB-INF/deploy/’: No such file or directory
mv: cannot stat ‘tmp/deploy/’: No such file or directory

i don't have a "deploy" folder in my ‘war/WEB-INF', Traccar-web running correctly
Can you tell me what to do ..?

**Comment by tananaev** [comment]
Have you compiled traccar-web? You need to click "GWT compile" in the Google menu.

**Comment by manee1982** [comment]
Now i have it, Thank you very much, God bless you

**Comment by manee1982** [comment]
Hello agin anton. One last thing.
----------------------------------------
After successfully building, packaging, and building a setup files. [linux-32, linux64, windows, mac]. there is a tracker-server-0.1.zip file in my 'traccar/setup', contains [README.txt, tracker-server.jar].
and there is some guides in the readme.txt file which i don't understand, it says:

- Web page - http://www.traccar.org
- This package contains only main Java application (tracker-server.jar).
- To start application you need libraries to lib folder (check manifest file)
- Create configuration file (more information on web page)
- To start application run following command:
java -jar tracker-server.jar "configuration.xml"

How to make this tracker-server run with/in my successfully built packages

**Comment by tananaev** [comment]
Ignore that one. Just use installer for your platform.

**Comment by manee1982** [comment]
OK thank you very much.

**Comment by chaitanya9186** [comment]
Where can I find this "configuration.xml"? Thank you

**Comment by tananaev** [comment]
Here is a config I use for development:
https://github.com/tananaev/traccar/blob/master/debug.xml

Here is production config for Linux:
https://github.com/tananaev/traccar/blob/master/setup/linux/traccar.cfg
