### ISSUE TITLE
Vehicle can't updating

### ISSUE THREAD

**Issue by adhasyuhada** [tananaev/traccar#1150]
I have server traccar for teltonika FM4200 that's device not updating in web client, why is it .?

**Comment by sunjije** [comment]
Please be more specific, what errors are you getting? Are the ports open from your server and what information is present in the log file?

**Comment by tananaev** [comment]
Please provide logs (tracker-server.log).

**Comment by adhasyuhada** [comment]
i used teltonika FM4200 with port 5027 that's have opened when i cheked http://www.tananaev.com/port.html
This log (tracker-server.log)

2013-10-17 14:33:45  INFO: Starting server...
2013-10-17 14:33:45  INFO: Operating System name: Linux version: 2.6.32-220.4.2.el6.i686 architecture: i386
2013-10-17 14:33:45  INFO: Java Runtime name: OpenJDK Server VM vendor: Oracle Corporation version: 23.7-b01
2013-10-17 14:33:45  INFO: Memory Limit heap: 910mb non-heap: 176mb
2013-10-17 14:34:24 DEBUG: [5002 <- 114.127.222.2] - HEX: 78780d0108647170025679760015143b0d0a
2013-10-17 14:34:54  INFO: Closing connection by disconnect
2013-10-17 14:35:42 DEBUG: [5023 <- 114.127.245.9] - HEX: 78780d010864717002567976001737290d0a
2013-10-17 14:35:42 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805010017ac6b0d0a
2013-10-17 14:35:44 DEBUG: [5023 <- 114.127.245.9] - HEX: 787825160d0a10120933c000ac64010b753b7d0010000901fe0a05f700542a100604020200189b990d0a
2013-10-17 14:35:44 DEBUG: [5023 -> 114.127.245.9] - HEX: 7878051600185d0c0d0a
2013-10-17 14:35:44  INFO: device: 1, time: Thu Oct 17 01:09:51 WIT 2013, lat: -6.276551666666666, lon: 106.79573166666667
2013-10-17 14:35:45 DEBUG: [5023 <- 114.127.245.9] - HEX: 78780a1345060400020019bec80d0a
2013-10-17 14:35:45 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780513001975380d0a
2013-10-17 14:35:46 DEBUG: [5023 <- 114.127.245.9] - HEX: 787825160d0a110b0e2fc900ac64250b753b530010000901fe0a05f700542a4c06040302001a0a9e0d0a
2013-10-17 14:35:46 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780516001a7e1e0d0a
2013-10-17 14:35:46  INFO: device: 1, time: Thu Oct 17 18:14:47 WIT 2013, lat: -6.276571666666666, lon: 106.79570833333334
2013-10-17 14:35:49 DEBUG: [5023 <- 114.127.245.9] - HEX: 787825160d0a10120924c800ac63fe0b753b7d0010000901fe0a05f700542a5006040202001b69d20d0a
2013-10-17 14:35:49 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780516001b6f970d0a
2013-10-17 14:35:49  INFO: device: 1, time: Thu Oct 17 01:09:36 WIT 2013, lat: -6.27655, lon: 106.79573166666667
2013-10-17 14:36:27 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a0b0f060fca00ac64040b753b3e00100001fe0a05f700542a001c9d1c0d0a
2013-10-17 14:36:27 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512001c78490d0a
2013-10-17 14:36:27  INFO: device: 1, time: Fri Oct 11 22:06:15 WIT 2013, lat: -6.276553333333333, lon: 106.79569666666667
2013-10-17 14:36:28 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a0b0f0618ca00ac64040b753b3b00100001fe0a05f700542a001d78920d0a
2013-10-17 14:36:28 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512001d69c00d0a
2013-10-17 14:36:28  INFO: device: 1, time: Fri Oct 11 22:06:24 WIT 2013, lat: -6.276553333333333, lon: 106.795695
2013-10-17 14:36:29 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a0b0f0622ca00ac64040b753b3b00100001fe0a05f700542a001e53bf0d0a
2013-10-17 14:36:29 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512001e5b5b0d0a
2013-10-17 14:36:29  INFO: device: 1, time: Fri Oct 11 22:06:34 WIT 2013, lat: -6.276553333333333, lon: 106.795695
2013-10-17 14:36:30 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1633c400ac64070b753bc500100001fe0a05f7005427001fc3550d0a
2013-10-17 14:36:30 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512001f4ad20d0a
2013-10-17 14:36:30  INFO: device: 1, time: Thu Oct 17 18:22:51 WIT 2013, lat: -6.276555, lon: 106.79577166666667
2013-10-17 14:36:31 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1700c700ac64100b753b4d00100001fe0a05f7005427002039450d0a
2013-10-17 14:36:31 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002083a60d0a
2013-10-17 14:36:31  INFO: device: 1, time: Thu Oct 17 18:23:00 WIT 2013, lat: -6.27656, lon: 106.795705
2013-10-17 14:36:32 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b170ac700ac64250b753b2600100001fe0a05f70054270021c7060d0a
2013-10-17 14:36:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120021922f0d0a
2013-10-17 14:36:32  INFO: device: 1, time: Thu Oct 17 18:23:10 WIT 2013, lat: -6.276571666666666, lon: 106.79568333333333
2013-10-17 14:36:33 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1714c700ac64280b753b2900100001fe0a05f700542a0022f7900d0a
2013-10-17 14:36:33 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120022a0b40d0a
2013-10-17 14:36:33  INFO: device: 1, time: Thu Oct 17 18:23:20 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:36:34 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b171fca00ac64280b753b2900100001fe0a05f700542a002364e90d0a
2013-10-17 14:36:34 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120023b13d0d0a
2013-10-17 14:36:34  INFO: device: 1, time: Thu Oct 17 18:23:31 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:36:35 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1728ca00ac64280b753b2900100001fe0a05f700542a0024d9230d0a
2013-10-17 14:36:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120024c5820d0a
2013-10-17 14:36:35  INFO: device: 1, time: Thu Oct 17 18:23:40 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:36:36 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1733c900ac64280b753b2900100001fe0a05f700542a00251b020d0a
2013-10-17 14:36:36 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120025d40b0d0a
2013-10-17 14:36:36  INFO: device: 1, time: Thu Oct 17 18:23:51 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:37:27 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1800ca00ac64280b753b2900100001fe0a05f700542a002666d30d0a
2013-10-17 14:37:27 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120026e6900d0a
2013-10-17 14:37:28 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b180bca00ac64280b753b2900100001fe0a05f700542a00278b1c0d0a
2013-10-17 14:37:28 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120027f7190d0a
2013-10-17 14:37:28  INFO: device: 1, time: Thu Oct 17 18:24:11 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:37:29 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b1815ca00ac64280b753b2900100001fe0a05f700542a0028ed7a0d0a
2013-10-17 14:37:29 DEBUG: [5023 -> 114.127.245.9] - HEX: 7878051200280fee0d0a
2013-10-17 14:37:29  INFO: device: 1, time: Thu Oct 17 18:24:21 WIT 2013, lat: -6.276573333333333, lon: 106.795685
2013-10-17 14:37:32 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a10111d15c400ac63350b753be000100001fe0a05f700542a002950440d0a78781f120d0a10111d1fc400ac63230b753bec00100001fe0a05f700542a002aff750d0a
2013-10-17 14:37:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 7878051200291e670d0a
2013-10-17 14:37:32  INFO: device: 1, time: Thu Oct 17 00:29:21 WIT 2013, lat: -6.276438333333333, lon: 106.79578666666667
2013-10-17 14:37:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002a2cfc0d0a
2013-10-17 14:37:32  INFO: device: 1, time: Thu Oct 17 00:29:31 WIT 2013, lat: -6.2764283333333335, lon: 106.79579333333334
2013-10-17 14:37:33 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a10111d29c400ac63350b753be300100001fe0a05f700542a002bc55b0d0a
2013-10-17 14:37:33 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002b3d750d0a
2013-10-17 14:37:33  INFO: device: 1, time: Thu Oct 17 00:29:41 WIT 2013, lat: -6.276438333333333, lon: 106.79578833333333
2013-10-17 14:37:35 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a10111d34c400ac633b0b753bda00100001fe0a05f700542a002ca2e10d0a78781f120d0a10111e02c600ac634a0b753bce00100001fe0a05f700542a002d48b50d0a78781f120d0a10111e0cc600ac63500b753bc500100001fe0a05f700542a002ea4e50d0a
2013-10-17 14:37:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002c49ca0d0a
2013-10-17 14:37:35  INFO: device: 1, time: Thu Oct 17 00:29:52 WIT 2013, lat: -6.276441666666667, lon: 106.79578333333333
2013-10-17 14:37:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002d58430d0a
2013-10-17 14:37:35  INFO: device: 1, time: Thu Oct 17 00:30:02 WIT 2013, lat: -6.27645, lon: 106.79577666666667
2013-10-17 14:37:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002e6ad80d0a
2013-10-17 14:37:35  INFO: device: 1, time: Thu Oct 17 00:30:12 WIT 2013, lat: -6.276453333333333, lon: 106.79577166666667
2013-10-17 14:37:36 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a10111e16c600ac63500b753bbf00100001fe0a05f700542a002f3e4b0d0a
2013-10-17 14:37:36 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512002f7b510d0a
2013-10-17 14:37:36  INFO: device: 1, time: Thu Oct 17 00:30:22 WIT 2013, lat: -6.276453333333333, lon: 106.79576833333333
2013-10-17 14:38:32 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a10111e20c600ac63560b753bbc00100001fe0a05f700542a003017cf0d0a78781f120d0a10111e2ac600ac63590b753bb900100001fe0a05f700542a0031fb420d0a78781f120d0a10111e34c600ac635c0b753bbc00100001fe0a05f700542a0032d9530d0a78781f120d0a110b2c2ec500ac64640b753b7700100001fe0a05f7005427003373430d0a78781f120d0a110b2c39c500ac64670b753b6200100001fe0a05f700542a0034db6b0d0a
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003093270d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 00:30:32 WIT 2013, lat: -6.276456666666666, lon: 106.79576666666667
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003182ae0d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 00:30:42 WIT 2013, lat: -6.276458333333333, lon: 106.795765
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120032b0350d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 00:30:52 WIT 2013, lat: -6.27646, lon: 106.79576666666667
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120033a1bc0d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 18:44:46 WIT 2013, lat: -6.276606666666667, lon: 106.79572833333333
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120034d5030d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 18:44:57 WIT 2013, lat: -6.276608333333333, lon: 106.79571666666666
2013-10-17 14:38:32 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2d07c500ac645e0b753b5900100001fe0a05f700542a0035b40b0d0a
2013-10-17 14:38:32 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120035c48a0d0a
2013-10-17 14:38:32  INFO: device: 1, time: Thu Oct 17 18:45:07 WIT 2013, lat: -6.276603333333333, lon: 106.79571166666666
2013-10-17 14:38:35 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2d10c500ac645e0b753b5900100001fe0a05f700542a0036ffc40d0a78781f120d0a110b2d1bc500ac64610b753b5900100001fe0a05f700542a003704530d0a78781f120d0a110b2d24c600ac64610b753b5c00100001fe0a05f700542a003825780d0a
2013-10-17 14:38:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120036f6110d0a
2013-10-17 14:38:35  INFO: device: 1, time: Thu Oct 17 18:45:16 WIT 2013, lat: -6.276603333333333, lon: 106.79571166666666
2013-10-17 14:38:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 787805120037e7980d0a
2013-10-17 14:38:35  INFO: device: 1, time: Thu Oct 17 18:45:27 WIT 2013, lat: -6.276605, lon: 106.79571166666666
2013-10-17 14:38:35 DEBUG: [5023 -> 114.127.245.9] - HEX: 7878051200381f6f0d0a
2013-10-17 14:38:35  INFO: device: 1, time: Thu Oct 17 18:45:36 WIT 2013, lat: -6.276605, lon: 106.79571333333334
2013-10-17 14:38:37 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2d2ec600ac64640b753b5900100001fe0a05f700542a0039cf650d0a
2013-10-17 14:38:37 DEBUG: [5023 -> 114.127.245.9] - HEX: 7878051200390ee60d0a
2013-10-17 14:38:37  INFO: device: 1, time: Thu Oct 17 18:45:46 WIT 2013, lat: -6.276606666666667, lon: 106.79571166666666
2013-10-17 14:38:44 DEBUG: [5023 <- 114.127.245.9] - HEX: 78780a134506040002003aad510d0a
2013-10-17 14:38:44 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780513003a66a10d0a
2013-10-17 14:39:28 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2d39c600ac64670b753b5600100001fe0a05f700542a003b0bff0d0a
2013-10-17 14:39:28 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003b2df40d0a
2013-10-17 14:39:28  INFO: device: 1, time: Thu Oct 17 18:45:57 WIT 2013, lat: -6.276608333333333, lon: 106.79571
2013-10-17 14:39:29 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2e07c600ac64670b753b5300100001fe0a05f700542a003c316f0d0a
2013-10-17 14:39:29 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003c594b0d0a
2013-10-17 14:39:29  INFO: device: 1, time: Thu Oct 17 18:46:07 WIT 2013, lat: -6.276608333333333, lon: 106.79570833333334
2013-10-17 14:39:30 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a110b2e10c600ac646a0b753b5300100001fe0a05f700542a003da5b50d0a
2013-10-17 14:39:30 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003d48c20d0a
2013-10-17 14:39:30  INFO: device: 1, time: Thu Oct 17 18:46:16 WIT 2013, lat: -6.27661, lon: 106.79570833333334
2013-10-17 14:39:31 DEBUG: [5023 <- 114.127.245.9] - HEX: 78781f120d0a0b0e251ec500ac64130b753b5000100001fe0a05f700542a003e3c8a0d0a
2013-10-17 14:39:31 DEBUG: [5023 -> 114.127.245.9] - HEX: 78780512003e7a590d0a
2013-10-17 14:39:31  INFO: device: 1, time: Fri Oct 11 21:37:30 WIT 2013, lat: -6.276561666666667, lon: 106.79570666666666
2013-10-17 14:39:32  INFO: Shutting down server...
2013-10-17 14:39:32  INFO: Closing connection by disconnect


and this one (tracker-server-gt06.log.20150331)

2015-03-31 13:35:29  INFO: Memory Limit heap: 910mb non-heap: 176mb
2015-03-31 13:37:54  INFO: Closing connection by disconnect
2015-03-31 13:38:02  INFO: Closing connection by disconnect
2015-03-31 14:14:46  INFO: Closing connection by disconnect
2015-03-31 14:14:48  INFO: Closing connection by disconnect
2015-03-31 14:14:50  INFO: Closing connection by disconnect
2015-03-31 14:24:04  INFO: Closing connection by disconnect
2015-03-31 15:32:09  INFO: Closing connection by disconnect
2015-03-31 15:40:50  INFO: Shutting down server...
2015-03-31 15:41:06  INFO: Starting server...
2015-03-31 15:41:06  INFO: Operating System name: Linux version: 2.6.32-220.4.2.el6.i686 architecture: i386
2015-03-31 15:41:06  INFO: Java Runtime name: OpenJDK Server VM vendor: Oracle Corporation version: 23.7-b01
2015-03-31 15:41:06  INFO: Memory Limit heap: 910mb non-heap: 176mb
2015-03-31 15:58:00  INFO: Closing connection by disconnect
2015-03-31 18:30:54  WARN: Connection reset by peer - java.io.IOException (FileDispatcherImpl.java:-2)
2015-03-31 18:30:54  INFO: Closing connection by exception
2015-03-31 18:30:54  INFO: Closing connection by disconnect



and this one (wrapper.log.20150401)
STATUS | wrapper  | 2015/04/01 08:13:22 | TERM trapped.  Shutting down.
STATUS | wrapper  | 2015/04/01 08:13:23 | <-- Wrapper Stopped
STATUS | wrapper  | 2015/04/01 08:38:58 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/04/01 08:38:58 | Java Service Wrapper Community Edition 32-bit 3.5.20
STATUS | wrapper  | 2015/04/01 08:38:58 |   Copyright (C) 1999-2013 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/04/01 08:38:58 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/04/01 08:38:58 |
STATUS | wrapper  | 2015/04/01 08:38:58 | Launching a JVM...
INFO   | jvm 1    | 2015/04/01 08:38:58 | WrapperManager: Initializing...

**Comment by tananaev** [comment]
There are no messages on port 5027. It means either your device doesn't send them or network (router/firewall) is not configured correctly. If you say that website says that the port is open, then probably the issue is on the device side.

**Comment by adhasyuhada** [comment]
my traccar integration with OpenGTS, last updated vehicle was 26 march 2015 when i reboot my server and then after that can't update.

**Comment by tananaev** [comment]
Well, as far as I can see it's not server problem.

**Comment by adhasyuhada** [comment]
Thank you i will checking on device

**Comment by adhasyuhada** [comment]
i have trouble again in my server can you help me sir ?

gt06.log

[INFO_|04/01 10:05:55|Main.main:178] Template Example Server Version 0.2.5
[INFO_|04/01 10:05:55|Main.main:179] DeviceCode           : gt06
[INFO_|04/01 10:05:55|Main.main:180] ParseFormat          : 1
[INFO_|04/01 10:05:55|Main.main:181] MinimumSpeed         : 0.0
[INFO_|04/01 10:05:55|Main.main:182] EstimateOdom         : true
[INFO_|04/01 10:05:55|Main.main:183] TCP Idle Timeout     : 10000 ms
[INFO_|04/01 10:05:55|Main.main:184] TCP Packet Timeout   : 4000 ms
[INFO_|04/01 10:05:55|Main.main:185] TCP Session Timeout  : 25000 ms
[INFO_|04/01 10:05:55|Main.main:186] UDP Idle Timeout     : 5000 ms
[INFO_|04/01 10:05:55|Main.main:187] UDP Packet Timeout   : 4000 ms
[INFO_|04/01 10:05:55|Main.main:188] UDP Session Timeout  : 60000 ms
[INFO_|04/01 10:05:55|Main.main:189] Copyright 2007-2012, GeoTelematic Solutions, Inc.
[INFO_|04/01 10:05:55|Main.main:190] --------------------------------------------------------------------------
[ERROR|04/01 10:05:55|TrackServer._startTCP:246] Exception: ServerSocket error
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
        at java.net.ServerSocket.bind(ServerSocket.java:336)
        at java.net.ServerSocket.<init>(ServerSocket.java:202)
        at org.opengts.util.ServerSocketThread.createServerSocket(ServerSocketThread.java:251)
        at org.opengts.util.ServerSocketThread.<init>(ServerSocketThread.java:354)
        at org.opengts.util.ServerSocketThread.<init>(ServerSocketThread.java:365)
        at org.opengts.servers.gt06.TrackServer._startTCP(TrackServer.java:244)
        at org.opengts.servers.gt06.TrackServer.<init>(TrackServer.java:180)
        at org.opengts.servers.gt06.TrackServer.startTrackServer(TrackServer.java:71)
        at org.opengts.servers.gt06.Main.main(Main.java:221)
[ERROR|04/01 10:05:55|TrackServer.<init>:183] TCP: Error binding to port: 5023
[WARN_|04/01 10:05:55|TrackServer.<init>:213] No active device communication listeners!
[WARN_|04/01 10:05:55|TrackServer.<init>:229] Ignoring CommandPort listener

teltonika.log

[INFO_|04/01 10:05:49|Main.main:178] Teltonika Server Version 1.0.0
[INFO_|04/01 10:05:49|Main.main:179] DeviceCode           : teltonika
[INFO_|04/01 10:05:49|Main.main:181] MinimumSpeed         : 3.0
[INFO_|04/01 10:05:49|Main.main:182] EstimateOdom         : true
[INFO_|04/01 10:05:49|Main.main:183] TCP Idle Timeout     : 3600000 ms
[INFO_|04/01 10:05:49|Main.main:184] TCP Packet Timeout   : 3600000 ms
[INFO_|04/01 10:05:49|Main.main:185] TCP Session Timeout  : 3600000 ms
[INFO_|04/01 10:05:49|Main.main:186] UDP Idle Timeout     : 5000 ms
[INFO_|04/01 10:05:49|Main.main:187] UDP Packet Timeout   : 4000 ms
[INFO_|04/01 10:05:49|Main.main:188] UDP Session Timeout  : 60000 ms
[INFO_|04/01 10:05:49|Main.main:189] Copyright 2007-2012, GeoTelematic Solutions, Inc.
[INFO_|04/01 10:05:49|Main.main:190] --------------------------------------------------------------------------
[ERROR|04/01 10:05:49|TrackServer._startTCP:249] Exception: ServerSocket error
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
        at java.net.ServerSocket.bind(ServerSocket.java:336)
        at java.net.ServerSocket.<init>(ServerSocket.java:202)
        at org.opengts.util.ServerSocketThread.createServerSocket(ServerSocketThread.java:251)
        at org.opengts.util.ServerSocketThread.<init>(ServerSocketThread.java:354)
        at org.opengts.util.ServerSocketThread.<init>(ServerSocketThread.java:365)
        at org.opengts.servers.teltonika.TrackServer._startTCP(TrackServer.java:247)
        at org.opengts.servers.teltonika.TrackServer.<init>(TrackServer.java:181)
        at org.opengts.servers.teltonika.TrackServer.startTrackServer(TrackServer.java:71)
        at org.opengts.servers.teltonika.Main.main(Main.java:221)
[ERROR|04/01 10:05:49|TrackServer.<init>:185] TCP: Error binding to port: 5027
[INFO_|04/01 10:05:49|DCServerConfig.startServerSocketThread:1132] Starting Event Listener (UDP) - 5027 [0.0.0.0/0.0.0.0] ...
[WARN_|04/01 10:05:49|TrackServer.<init>:232] Ignoring CommandPort listener

**Comment by tananaev** [comment]
What logs are these? It doesn't look like Traccar logs.

**Comment by adhasyuhada** [comment]
my traccar integration with OpenGTS, but i don't have any response in another side

**Comment by adhasyuhada** [comment]
![traccar](https://cloud.githubusercontent.com/assets/11660402/6937585/7e9eb3c6-d886-11e4-89d9-4040623d2462.png)
#traccar/logs

**Comment by tananaev** [comment]
The ones you provided above (gt06.log and teltonika.log) are not Traccar logs.

**Comment by adhasyuhada** [comment]
This one right ? "tracker-server.log"
2015-04-01 15:50:35  INFO: Starting server...
2015-04-01 15:50:35  INFO: Operating System name: Linux version: 2.6.32-220.4.2.el6.i686 architecture: i386
2015-04-01 15:50:35  INFO: Java Runtime name: OpenJDK Server VM vendor: Oracle Corporation version: 23.7-b01
2015-04-01 15:50:35  INFO: Memory Limit heap: 910mb non-heap: 176mb
2015-04-01 16:03:46  INFO: Shutting down server...
2015-04-01 16:03:50  INFO: Starting server...
2015-04-01 16:03:50  INFO: Operating System name: Linux version: 2.6.32-220.4.2.el6.i686 architecture: i386
2015-04-01 16:03:50  INFO: Java Runtime name: OpenJDK Server VM vendor: Oracle Corporation version: 23.7-b01
2015-04-01 16:03:50  INFO: Memory Limit heap: 910mb non-heap: 176mb

**Comment by tananaev** [comment]
No HEX messages in the log means server haven't received any data from devices.

**Comment by tananaev** [comment]
In case someone has a problem with device updates, here is the troubleshooting guide:

https://www.traccar.org/troubleshooting/
