### ISSUE TITLE
Github code vs. http://demo.traccar.org/

### ISSUE THREAD

**Issue by cagryInside** [tananaev/traccar#1162]
Hi, 
I clone the traccar server and web projects from the repo, and followed the installation guide. Then, I run the application from eclipse. However, after I run the application, I see some differences between http://demo.traccar.org/ and my local app.
1. App didn't create the DB tables automatically. `createDatabaseSchema()` method in the `DataManager` never used anywhere in the project. So, I had to modify the code and create by myself.
2. After the app start, I couldn't register a user. In `DataManager` there is no register method. So, I manually insert a user into the DB.
3. After logging in the web app, I see totally different UI. And, there is no side menus:
   ![screen shot 2015-04-10 at 12 14 55 pm](https://cloud.githubusercontent.com/assets/2777974/7091902/7b70be3c-df7b-11e4-8b9e-a3db5fecfea3.png)

I forked the traccar (https://github.com/tananaev/traccar/tree/master) and traccar-web (https://github.com/tananaev/traccar-web) projects, and using the master branch (actually, there is no other branches).

Thanks for any guidance and/or help.

**Comment by tananaev** [comment]
You need to change `http.new` to `false` in the config file to go back to the old web interface.

**Comment by cagryInside** [comment]
@tananaev I change the config to ```false```. But now, I am getting following error:

```
2015-04-10 23:03:54.886:INFO:oejw.WebInfConfiguration:Extract jar:file:/Users/cagryInside/Desktop/traccar-server/traccar-web/traccar-web.war!/ to /private/var/folders/wb/4zkkhgxx5cd_cz36qq3g668c0000gn/T/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp
2015-04-10 23:03:56.695:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2015-04-10 23:03:56.735:WARN:oejs.Holder:
java.lang.ClassNotFoundException: org.traccar.web.server.model.DataServiceImpl
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:100)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:79)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:107)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.traccar.http.WebServer.start(WebServer.java:91)
	at org.traccar.ServerManager.start(ServerManager.java:196)
	at org.traccar.Main.main(Main.java:34)
2015-04-10 23:03:56.736:WARN:/:unavailable
javax.servlet.UnavailableException: org.traccar.web.server.model.DataServiceImpl
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:114)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.traccar.http.WebServer.start(WebServer.java:91)
	at org.traccar.ServerManager.start(ServerManager.java:196)
	at org.traccar.Main.main(Main.java:34)
```

**Comment by tananaev** [comment]
Looks like you have some problem with database connection now.

**Comment by cagryInside** [comment]
Thanks @tananaev . I resolved couple issues and now it looks like working: 
```
2015-04-13 11:52:19.226:INFO::jetty-7.2.2.v20101205
2015-04-13 11:52:19.266:INFO::Extract jar:file:/Users/cagryInside/Desktop/traccar-server/traccar-web/traccar-web.war!/ to /private/var/folders/wb/4zkkhgxx5cd_cz36qq3g668c0000gn/T/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp
2015-04-13 11:52:20.698:INFO::Started SelectChannelConnector@0.0.0.0:8082
```
However, when I go to ```localhost:8082``` from the browser, I get blank screen: 
![screen shot 2015-04-13 at 11 52 39 am](https://cloud.githubusercontent.com/assets/2777974/7119476/d628cf2c-e1d3-11e4-9628-35530c225125.png)

**Comment by tananaev** [comment]
Looks like it's still trying to load new interface. Try to clear browser cache.
