### ISSUE TITLE
2 errors occur when compiling packages

### ISSUE THREAD

**Issue by gpsim** [tananaev/traccar#1472]
Failed tests:   testDecode(org.traccar.protocol.AdmProtocolDecoderTest): speed <= 869
  testDecode(org.traccar.protocol.Gt06ProtocolDecoderTest): time expected:<Tue Oct 20 22:21:11 CST 2015> but was:<Tue Oct 20 14:21:11 CST 2015>

Tests run: 119, Failures: 2, Errors: 0, Skipped: 0

**Comment by tananaev** [comment]
It passes for me now. Can you please get latest source and try again.

**Comment by gpsim** [comment]
Has been updated, but still the same error

-------------------------------------------------------------------------------
Test set: org.traccar.protocol.AdmProtocolDecoderTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE!
testDecode(org.traccar.protocol.AdmProtocolDecoderTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: speed <= 869
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.traccar.ProtocolDecoderTest.verifyDecodedPosition(ProtocolDecoderTest.java:172)
	at org.traccar.ProtocolDecoderTest.verifyPosition(ProtocolDecoderTest.java:61)
	at org.traccar.protocol.AdmProtocolDecoderTest.testDecode(AdmProtocolDecoderTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by tananaev** [comment]
Are you sure you don't have any custom changes? It works for me and Travis CI doesn't report any issues.
