### ISSUE TITLE
Failed to start Traccar 3.2

### ISSUE THREAD

**Issue by cascajo** [tananaev/traccar#1557]
When I try to start the version 3.2, the wrapper gives me an error and stops, this is the log:
STATUS | wrapper  | 2015/11/26 10:43:49 | --> Wrapper Started as Console
STATUS | wrapper  | 2015/11/26 10:43:49 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2015/11/26 10:43:49 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/11/26 10:43:49 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/11/26 10:43:49 | 
STATUS | wrapper  | 2015/11/26 10:43:49 | Launching a JVM...
INFO   | jvm 1    | 2015/11/26 10:43:49 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/11/26 10:43:50 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/11/26 10:43:50 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/11/26 10:43:50 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge14i9din0mtg1d74xw9|6e97727d, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge14i9din0mtg1d74xw9|6e97727d, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:C:\Program Files (x86)\Traccar\data\database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: java.lang.RuntimeException
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:177)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:63)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:112)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/11/26 10:43:51 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
STATUS | wrapper  | 2015/11/26 10:43:53 | <-- Wrapper Stopped
What should I do to prevent this happening to me?
Thank you

**Comment by tananaev** [comment]
Looks like you haven't updated the database schema.

**Comment by cascajo** [comment]
I'm doing a clean install not a update
Thanks

**Comment by tananaev** [comment]
What database are you using?

**Comment by cascajo** [comment]
I am using mysql, I deleted all the tables, and started all over again, and now the server run correctly, but when I access by 127.0.0.1:8082, tells me 'wrong procedure call'

**Comment by tananaev** [comment]
Can you make a screenshot?

**Comment by cascajo** [comment]
This is my capture, and the logs

Thanks

**Comment by tananaev** [comment]
Please attach it on GitHub comment.

**Comment by sosoxuc** [comment]
Port 5004 is used by another service as it seems from logs

Shut down other service to free port

**Comment by tananaev** [comment]
@sosoxuc is right. Service failed to start because you have some other process that uses port 5004. Also, seems like you are not using official Traccar web interface. Next time please specify it explicitly instead of saying that you are using just version 3.2.
