### ISSUE TITLE
Configuration with MS SQL Server Database

### ISSUE THREAD

**Issue by ilevans** [tananaev/traccar#1617]
I have tried installing V3.3 and am receiving the following. the `sqljdbc4.jar` file is installed in the lib folder.

```
STATUS | wrapper  | 2015/12/24 05:08:44 | --> Wrapper Started as Service
STATUS | wrapper  | 2015/12/24 05:08:44 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/12/24 05:08:44 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/12/24 05:08:44 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/12/24 05:08:44 | 
STATUS | wrapper  | 2015/12/24 05:08:44 | Launching a JVM...
INFO   | jvm 1    | 2015/12/24 05:08:45 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/12/24 05:08:46 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/12/24 05:08:46 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:160)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: Caused by: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:199)
INFO   | jvm 1    | 2015/12/24 05:08:46 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2015/12/24 05:08:49 | <-- Wrapper Stopped
```
The traccar.xml file includes the following database definition which worked with V3.2.
```
    <!-- DATABASE CONFIG -->

	<entry key='database.driverFile'>C:\Program Files (x86)\Traccar\lib\sqljdbc4.jar</entry>
	<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
	<entry key='database.url'>jdbc:sqlserver://localhost;user=traccar;password=traccar;</entry>
	<entry key='database.user'>traccar</entry>
	<entry key='database.password'>traccar</entry>
```

**Comment by tananaev** [comment]
Please try this build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by ilevans** [comment]
Anton

I am just off to work so will try it tonight when I get home.

Merry Christmas

Ian

**Comment by ilevans** [comment]
I tested the new version and it worked after manually intervention with the database upgrade.  
Details of the database upgrade errors sent via e-mail.

**Comment by ilevans** [comment]
Anton, the update that you provided me works perfectly in upgrading the MS SQL database.

thanks, Ian

**Comment by tananaev** [comment]
Thanks for all the feedback.

Unfortunately it doesn't work for updating from older version to the new one, but I'll try to find a solution.

**Comment by RRodrigoR** [comment]
Hi Anton, I have the same issue,and sqljdbc4.jar file is installed in the lib folder. I try use you build (https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0)   

but I get the same log:
INFO   | jvm 1    | 2016/03/27 19:50:34 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/03/27 19:50:35 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/03/27 19:50:35 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:160)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: Caused by: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:199)
INFO   | jvm 1    | 2016/03/27 19:50:36 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2016/03/27 19:50:38 | <-- Wrapper Stopped


Can you help me?

**Comment by tananaev** [comment]
@RRodrigoR, this is a very old thread. Please install latest official release and don't use `.jar` file from this thread.

**Comment by RRodrigoR** [comment]
thanks,I forget see the date of this thread
