### ISSUE TITLE
stoped traccar crash

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1641]
is there any solution as below error ? it's happen in few days or around in week and there is like 80 devices  only 

around 8 days happen like this 

6/01/06 00:36:17 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:17 | 
INFO   | jvm 1    | 2016/01/06 00:36:18 | Jan 06, 2016 12:36:17 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:18 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:18 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:18 | 
INFO   | jvm 1    | 2016/01/06 00:36:19 | Jan 06, 2016 12:36:18 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:19 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:19 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:19 | 
INFO   | jvm 1    | 2016/01/06 00:36:20 | Jan 06, 2016 12:36:19 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:20 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:20 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:20 | 
INFO   | jvm 1    | 2016/01/06 00:36:21 | Jan 06, 2016 12:36:20 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:21 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:21 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:21 | 
INFO   | jvm 1    | 2016/01/06 00:36:22 | Jan 06, 2016 12:36:21 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:22 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:22 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:22 | 
INFO   | jvm 1    | 2016/01/06 00:36:23 | Jan 06, 2016 12:36:22 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:23 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:23 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:23 | 
INFO   | jvm 1    | 2016/01/06 00:36:24 | Jan 06, 2016 12:36:23 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:24 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:24 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:24 | 
INFO   | jvm 1    | 2016/01/06 00:36:25 | Jan 06, 2016 12:36:24 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:25 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:25 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:25 | 
INFO   | jvm 1    | 2016/01/06 00:36:26 | Jan 06, 2016 12:36:25 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:26 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:26 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:26 | 
INFO   | jvm 1    | 2016/01/06 00:36:27 | Jan 06, 2016 12:36:26 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:27 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:27 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:27 | 
INFO   | jvm 1    | 2016/01/06 00:36:28 | Jan 06, 2016 12:36:27 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:28 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:28 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:28 | 
INFO   | jvm 1    | 2016/01/06 00:36:29 | Jan 06, 2016 12:36:28 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:29 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:29 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:29 | 
INFO   | jvm 1    | 2016/01/06 00:36:30 | Jan 06, 2016 12:36:29 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:30 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:30 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:30 | 
INFO   | jvm 1    | 2016/01/06 00:36:31 | Jan 06, 2016 12:36:30 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:31 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:31 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/06 00:36:31 | 
INFO   | jvm 1    | 2016/01/06 00:36:32 | Jan 06, 2016 12:36:31 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/01/06 00:36:32 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/01/06 00:36:32 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/06 00:36:32 | 	at java.util.concurrent.ThreadPoolExecutor

**Comment by tananaev** [comment]
This error means that you have reached maximum number of connections allowed by operating system.

One option is to use `resetDelay` parameter in the config. It's basically an idle connection timeout.

**Comment by perfectwebtech** [comment]
u mean resetDelay will solve problem ?


and this thing also could be helpfull ? 

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
http://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user

**Comment by tananaev** [comment]
Yes, all of those things should help. Note that Traccar usually runs as a root user on Linux.

**Comment by perfectwebtech** [comment]
is there any monitoring system i can manage for server crash or if stop port something ?

**Comment by tananaev** [comment]
There must be some standard system tools that you can use to monitor service status.

**Comment by perfectwebtech** [comment]
hello
which file is can get response of command in web  just not true false example  current location
i can see in log response so from java which files i can get command response ? 

example in api method where can get those values not only true false  need actualy value in api as below current position for location so is there in api something i can get ?  over api files ? 

Current position! Lat:N27.565765,Lon:E76.073227,Course:166.39,Speed:0.00Km/h,DateTime:2016-01-26 14:10:23

787875156d0000000043757272656e7420706f736974696f6e21204c61743a4e32372e3536353736352c4c6f6e3a4537362e3037333232372c436f757273653a3136362e33392c53706565643a302e30304b6d2f682c4461746554696d653a323031362d30312d32362031343a31303a323300020821d8fe0d0a

**Comment by tananaev** [comment]
You can receive device responses in decoder class.

**Comment by vbonne** [comment]
Hi !
I have the same issue with the  " Too many open files" error.

How can I set the  "resetDelay " ? in which config file ? and what is the sintax ?
I already increased the files decriptors for root to 40.000 but does not help...

Many thanks !

**Comment by vbonne** [comment]
also what would be a good value for resetDelay ?
I only have 10 devices and traccar halts on the "too many open files" error after about 3 days...

**Comment by tananaev** [comment]
The parameter has been renamed to "timeout". More info here:

https://www.traccar.org/configuration-file/

**Comment by vbonne** [comment]
Thank Anton,
I will test this right away.
Great project by the way ;)
