### ISSUE TITLE
MySQL снова

### ISSUE THREAD

**Issue by moroq** [tananaev/traccar#1650]
Привет, коллеги. Бла-бла про очень крутой софт и так далее опущу - лучше donate)
Помогите, пожалуйста, перекинуть на MySQL.

Последовательность такая:
1. Только что скачал с сайта, запустил, установилось нормально.
2. Не запуская беру с сайта же сниппет про MySQL, подставляю данные (проверил `&amp;` на месте). База существует, пользователь granted
3. Не поднимается. wrapper.log целиком ниже, он небольшой.
4. В базе появляются две таблицы DATABASECHANGELOG и DATABASECHANGELOGLOCK.

Я не работаю с Java, мне используемые принципы не знакомы. Однако видно, что xml файлы в ./data описывают как раз базу данных. И я вижу что 3.0.xml - еще здоровые VARCHARы на 1024, а в 3.1.xml - явно обновление, но до него дело то не доходит. Я внимательно прочитал всю историю у вас с длинными VARCHARами - и вижу, что в логах идет попытка создать таблицы с неподходящими параметрами. А ведь вроде решена проблема уже? Или как-то не так решена? Или я что-то не так делаю?

wrapper.log
```
STATUS | wrapper  | 2016/01/09 22:09:07 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/01/09 22:09:07 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2016/01/09 22:09:07 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/01/09 22:09:07 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/01/09 22:09:07 | 
STATUS | wrapper  | 2016/01/09 22:09:08 | Launching a JVM...
INFO   | jvm 1    | 2016/01/09 22:09:08 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/01/09 22:09:08 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/01/09 22:09:09 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/01/09 22:09:10 | INFO 1/9/16 10:09 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/01/09 22:09:11 | INFO 1/9/16 10:09 PM: liquibase: Reading from c0_skiltrade.DATABASECHANGELOG
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:11 | WARNING 1/9/16 10:09 PM: liquibase: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
INFO   | jvm 1    | 2016/01/09 22:09:12 | SEVERE 1/9/16 10:09 PM: liquibase: /opt/traccar/data/db.changelog-master.xml: /opt/traccar/data/db.changelog-3.0.xml::changelog-3.0::author: Change Set /opt/traccar/data/db.changelog-3.0.xml::changelog-3.0::author failed.  Error: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE c0_skiltrade.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/09 22:09:12 | liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE c0_skiltrade.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.Liquibase.update(Liquibase.java:212)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:169)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/09 22:09:12 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
INFO   | jvm 1    | 2016/01/09 22:09:12 | 	... 20 more
INFO   | jvm 1    | 2016/01/09 22:09:12 | INFO 1/9/16 10:09 PM: liquibase: /opt/traccar/data/db.changelog-3.0.xml::changelog-3.0::author: Successfully released change log lock
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set /opt/traccar/data/db.changelog-3.0.xml::changelog-3.0::author:
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE c0_skiltrade.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:590)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.Liquibase.update(Liquibase.java:212)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:169)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: Caused by: liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE c0_skiltrade.user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1024) NOT NULL, email VARCHAR(256) NOT NULL, hashedPassword VARCHAR(1024) NOT NULL, salt VARCHAR(1024) DEFAULT '' NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(1024) DEFAULT 'osm' NOT NULL, language VARCHAR(1024) DEFAULT 'en' NOT NULL, distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL, speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (id), UNIQUE (email))]
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	... 15 more
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
INFO   | jvm 1    | 2016/01/09 22:09:12 | WrapperSimpleApp Error: 	... 20 more
STATUS | wrapper  | 2016/01/09 22:09:14 | <-- Wrapper Stopped
```

**Comment by moroq** [comment]
Извиняюсь за лог - надеюсь, что и так понятно.

**Comment by tananaev** [comment]
Попробуй следующий запрос выполнить перед тем как запустить Traccar:

```
SET @@global.innodb_large_prefix = 1;
```

**Comment by moroq** [comment]
root@skil:~# /etc/init.d/traccar status
traccar is running: PID:30178, Wrapper:STARTED, Java:STARTED

Да, сервер стартанул, но это не привело к созданию таблиц и если я правильно понимаю, проблема сохраняется.

[wrapper.log.20160110.txt](https://github.com/tananaev/traccar/files/83858/wrapper.log.20160110.txt)

**Comment by tananaev** [comment]
На сколько я вижу проблема таже самая.

**Comment by moroq** [comment]
абслоютно. сервер MySQL показывает, что innodb_large_prefix - ON

**Comment by tananaev** [comment]
А какая версия MySQL установлена?

**Comment by moroq** [comment]
Сервер: Localhost via UNIX socket
Тип сервера: MySQL
Версия сервера: 5.5.44-0+deb8u1 - (Debian)
Версия протокола: 10
Пользователь: root@localhost
Кодировка сервера: UTF-8 Unicode (utf8)

**Comment by tananaev** [comment]
Странно. Может перезапустить сервер надо чтобы применилась настройка?

Еще один вариант это пойти и вручную поменять размер полей в changelog файлах.

**Comment by moroq** [comment]
Ну вот. В общем сервер стартанул нормально на MySQL только после того, как я поменял во всех xml в папке data значения VARCHAR(1024) и VARCHAR(256) на VARCHAR(128).

Я могу быть не прав и готов это признать, но вот эта версионная система с обновлениями структуры таблиц в БД - она не срабатывает. Логично предположить, что чтобы обновить структуру на VARCHAR(128) должна существовать таблица, которая в этом случае создается с недопустимой длинной VARCHAR. Странно в общем.
Но спасибо, донейт на подходе))

**Comment by tananaev** [comment]
Проблема в том что в версии 3.0 длина поля было 1024. Это работает на некоторых MySQL. Возможно дело в каких-то настройках. Соотвественно в changelog мне нужно прописать изначально размер поля 1024, а потом обновить его до текущего значения.

Скорее всего в следующей версии я поменяю changelog потому что у многих возникают проблемы.
