### ISSUE TITLE
gps306 obd data

### ISSUE THREAD

**Issue by ekofficiel** [tananaev/traccar#1672]
hi anton, i ve read on one post that we can use port 5001 for this device, but this device send many data like fuel, temperature, drive id, engine status... that are not implemented in traccar. How can we handle those data?

**Comment by tananaev** [comment]
Chinese manufacturers can use same model name for completely different devices, so you need to try and see if it's actually using GPS103 protocol.

As for additional data, Traccar supports additional data for some protocols.

**Comment by joseant** [comment]
Hello.
I have the gps306 obd too, this is the manual:
http://es.scribd.com/doc/226139496/GPS-306#scribd

I have seen in the logs, that send 2 mesages, the first one send gps data, the second one send the obd data.
If I use the hex decoder:
The first one:
imei:862106025096131,tracker,160120101247,,F,091310.000,A,3934.3780,N,00236.8443,E,0.01,162.18,,0,0,0.0%,,;

The second one:
imei:862106025096131,OBD,160120101248,13,,38823.5,,000,0.0%,+,0.0%,00000,12.9,,,,;

It is any way to get the obd data?

Thanks.

**Comment by tananaev** [comment]
All those extra fields should be stored in `attributes` column in the database.

By not stored you mean additional attributes are not stored or the whole message is ignored?

**Comment by joseant** [comment]
Hello Anton.
Thanks for the answer.

The field arributes has this values: 
{"alarm":"tracker","io1":"0","io2":"0","io3":"0.0%","ip":"90.174.2.21"}
It just store  the first data, the second one is not stored.

Thanks.

**Comment by tananaev** [comment]
Now I understand the problem. The OBD type is not supported yet. I need protocol documentation to add support for it.

**Comment by joseant** [comment]
Hello.
I cann`t find the protocol, but I know what means each number:
imei:862106025096131,OBD,160120101248,13,,38823.5,,000,0.0%,+,0.0%,00000,12.9,,,,;
imei:862106025096131,OBD,160120101248,a,b,c,d,e,f,g,h,i,j,,,,;
a-> ODOMETER 
b-> remaining fuel
c-> Average fuel
d-> driving time
e-> speed
f-> Power load
g-> water temp
h-> Throttle percentage
i-> engine speed
j-> Battry voltage

in the logs I got this:

2016-01-20 11:59:17 DEBUG: [CA7E23D3: 5001 > 90.174.2.21] HEX: 4f4e
2016-01-20 11:59:44 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c747261636b65722c3136303132303131353934302c2c462c3130353934322e3030302c412c333933342e333737332c4e2c30303233362e383436312c452c302e30302c3136322e31382c2c302c302c302e30252c2c3b
2016-01-20 11:59:44  INFO: [CA7E23D3] id: 1, time: 2016-01-20 11:59:42, lat: 39.57296, lon: 2.61410, speed: 0.0, course: 162.2
2016-01-20 11:59:47 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c4f42442c3136303132303131353934312c31332c2c33383832332e352c2c3030302c302e30252c2b2c302e30252c30303030302c31322e392c2c2c2c3b
2016-01-20 12:00:15 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c747261636b65722c3136303132303132303031302c2c462c3131303031332e3030302c412c333933342e333737332c4e2c30303233362e383436312c452c302e30312c3136322e31382c2c302c302c302e30252c2c3b
2016-01-20 12:00:15  INFO: [CA7E23D3] id: 1, time: 2016-01-20 12:00:13, lat: 39.57296, lon: 2.61410, speed: 0.0, course: 162.2
2016-01-20 12:00:18 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c4f42442c3136303132303132303031312c31332c2c33383832332e352c2c3030302c302e30252c2b2c302e30252c30303030302c31322e392c2c2c2c3b
2016-01-20 12:00:19 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 3836323130363032353039363133343b
2016-01-20 12:00:19 DEBUG: [CA7E23D3: 5001 > 90.174.2.21] HEX: 4f4e
2016-01-20 12:00:46 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c747261636b65722c3136303132303132303034302c2c462c3131303034342e3030302c412c333933342e333737342c4e2c30303233362e383436312c452c302e30322c3136322e31382c2c302c302c302e30252c2c3b
2016-01-20 12:00:46  INFO: [CA7E23D3] id: 1, time: 2016-01-20 12:00:44, lat: 39.57296, lon: 2.61410, speed: 0.0, course: 162.2
2016-01-20 12:00:49 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c4f42442c3136303132303132303034312c31332c2c33383832332e352c2c3030302c302e30252c2b2c302e30252c30303030302c31322e392c2c2c2c3b
2016-01-20 12:01:17 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c747261636b65722c3136303132303132303131302c2c462c3131303131352e3030302c412c333933342e333737342c4e2c30303233362e383436322c452c302e30312c3136322e31382c2c302c302c302e30252c2c3b
2016-01-20 12:01:17  INFO: [CA7E23D3] id: 1, time: 2016-01-20 12:01:15, lat: 39.57296, lon: 2.61410, speed: 0.0, course: 162.2
2016-01-20 12:01:20 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 696d65693a3836323130363032353039363133342c4f42442c3136303132303132303131312c31332c2c33383832332e352c2c3030302c302e30252c2b2c302e30252c30303030302c31322e392c2c2c2c3b
2016-01-20 12:01:21 DEBUG: [CA7E23D3: 5001 < 90.174.2.21] HEX: 3836323130363032353039363133343b
2016-01-20 12:01:21 DEBUG: [CA7E23D3: 5001 > 90.174.2.21] HEX: 4f4e
,13, -> ODOMETER

**Comment by tananaev** [comment]
I need to know possible value ranges. What does "+" mean? What values can be decimal. Are they always decimal?

**Comment by joseant** [comment]
+ means water temperature but the car is off know, so the gps just send +
The decimal, I need to use the car a little bit, to know it.
I will tell you later.

I have send an email to the seller ask him for the protocol document, but I am not very optimist in his answer.

**Comment by netomx** [comment]
jose, any link for those gps with odb? looks pretty nice!

**Comment by tejno** [comment]
http://www.aliexpress.com/item/GPS-GSM-GPRS-Tracking-OBD-Vehicle-Tracker-GPS306B-goole-SMS-Real-time-tracking-2-4G-attendance/2049728393.html?spm=2114.01010208.3.11.PiEb39&ws_ab_test=searchweb201556_1,searchweb201644_2_10001_10002_10005_9909_301_10006_9706_10003_10004_9906_62,searchweb201560_5,searchweb1451318400_6148,searchweb1451318411_6452

**Comment by emorfam** [comment]
Any update on this issue?

**Comment by tananaev** [comment]
Yes, OBD support is implemented for GPS103 protocol.

**Comment by wico** [comment]
May I ask a stupid question? I also have that coban 306A and in the H2DB (database.mv.db) I can see stored OBD-data (e.g. "temp1" and so on). So it looks like the device can send OBD-data.

How do I access that though the web-ui? :)

**Comment by tananaev** [comment]
You should be able to see it in the device state panel.

**Comment by wico** [comment]
Interessant. In state I can see e.g. a "Io4" which actually shows an OBD value I can sniff using tcpdump. But there are way more values coming in via GPRS, those are not shown in state.

**Comment by wico** [comment]
Sorry for the many updates of my comment above. I really hope I can help with the debuggings I've made.

**Comment by tananaev** [comment]
It happens because your device sends OBD data and regular GPS data messages as well. The one you "sniffed" is an OBD message. The one that you are looking at in the web interface is a regular GPS message.

**Comment by wico** [comment]
Yes. But sending of OBD data and GPS data is the expected behavior - or? Or is traccar not able to display the OBD-data messages?

**Comment by tananaev** [comment]
It should display both, but the one you are looking at is regular GPS message.

Make sure that you are using latest version and don't have filtering enabled in the config.

**Comment by wico** [comment]
I use that version: traccar-linux-32-3.7.zip

pulsar:/usr/local/traccar/conf# cat traccar.xml |grep -i filter|wc -l                                                                                                                                              
0

== There is no filtering set in the config.

Now I'm out of ideas and a bit confused. Where in the web-ui is the OBD-data shown id the "state" only displays the GPS-data?

**Comment by tananaev** [comment]
Can you provide your tracker-server log file. Please upload it somewhere instead of pasting the whole thing here.

**Comment by wico** [comment]
I have sent you an email with the whole logs.

**Comment by wico** [comment]
Beside of the mail I've sent, here an additional log:

```
sql> SELECT * FROM POSITIONS;
ID | PROTOCOL | DEVICEID | SERVERTIME              | DEVICETIME            | FIXTIME               | VALID | LATITUDE           | LONGITUDE          | ALTITUDE | SPEED | COURSE | ADDRESS                                             | ATTRIBUTES
1  | gps103   | 1        | 2016-09-16 13:06:13.321 | 2016-09-16 13:06:11.0 | 2016-09-16 13:06:11.0 | TRUE  | XX.602826666666665 | YY.764176666666668 | 0.0      | 0.01  | 305.6  | XXX                                                 | {"io1":"0","io2":"0","ip":"1.2.3.4","distance":0.0,"totalDistance":0.0}
2  | gps103   | 1        | 2016-09-16 13:31:28.727 | 2016-09-16 13:31:26.0 | 2016-09-16 13:31:26.0 | TRUE  | XX.60281666666667  | YY.764235          | 0.0      | 0.03  | 0.0    | XXX                                                 | {"io1":"1","io2":"0","ip":"1.2.3.4","distance":3.47,"totalDistance":3.47}
3  | gps103   | 1        | 2016-09-16 13:32:46.886 | 2016-09-16 13:32:45.0 | 2016-09-16 13:32:45.0 | TRUE  | XX.60281833333333  | YY.764233333333333 | 0.0      | 0.01  | 0.0    | XXX                                                 | {"io1":"1","io2":"0","io4":"125608","ip":"1.2.3.4","distance":0.21,"totalDistance":3.68}
4  | gps103   | 1        | 2016-09-16 13:32:47.807 | 2016-09-16 13:32:45.0 | 2016-09-16 13:32:45.0 | TRUE  | XX.60281833333333  | YY.764233333333333 | 0.0      | 0.01  | 0.0    | XXX                                                 | {"odometer":125608,"hours":"94","obdSpeed":"0","temp1":"25","throttle":"83.92%","rpm":"889","battery":"14.70","ip":"1.2.3.4","distance":0.0,"totalDistance":3.68}
5  | gps103   | 1        | 2016-09-16 13:35:30.037 | 2016-09-16 13:35:28.0 | 2016-09-16 13:35:28.0 | TRUE  | XX.60281666666667  | YY.764233333333333 | 0.0      | 0.02  | 0.0    | XXX                                                 | {"io1":"0","io2":"0","ip":"1.2.3.4","distance":0.19,"totalDistance":3.87}

```

ID #4 seems to contain OBD-values, the rest not. I will check asap if under "State" these are shown for some moment until ID #5 comes in with less values.

Not sure if that helps ...

**Comment by wico** [comment]
Okay, sorry for the noise. I think I have had a flaw in understanding how "State" works. :)

So, for the records: OBD-data is logged in a proper way and stored in the datebase. All fine.

To access them, one has to e.g. generate a report for a route (using a specific timeframe), thats doable vie the web-ui. Within that report, some (!) datapoints contain OBD-data, the rest ordinary GPS-data. Its then just about to go through the route and see what the OBD values are shown (if any).

For future one could implement some sort of a "chart diagram" in traccar to visualize that somehow.

**Comment by tananaev** [comment]
I have found one problem (21be926af517a09d91cb39fde45fb18a1a1cdfe9). Because timestamp is the same, Traccar was not updating the last position. Should be fixed now.

If you want to try, you can use this build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by wico** [comment]
You rock! I now run with the dropbox-version. Lets see. :)

**Comment by federicobalm** [comment]
Hello Anton.
try replacing the file tracker-server.jar you left on the link https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0.

before replacing the file traccar stopped, then replace the file-server tracker, jar, but then you can not start traccar

> root@webserver02:~# sudo /opt/traccar/bin/traccar start
Starting traccar...
Waiting for traccar......
WARNING: traccar may have failed to start.
root@webserver02:~#
> 

in the wrapper log:

> STATUS | wrapper  | 2016/10/03 12:32:00 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/10/03 12:32:00 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/03 12:32:00 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/03 12:32:00 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/03 12:32:00 | 
STATUS | wrapper  | 2016/10/03 12:32:00 | Launching a JVM...
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: java.lang.NoClassDefFoundError: com/ning/http/client/AsyncHttpClient
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at org.traccar.Context.<clinit>(Context.java:128)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: Caused by: java.lang.ClassNotFoundException: com.ning.http.client.AsyncHttpClient
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
INFO   | jvm 1    | 2016/10/03 12:32:00 | WrapperSimpleApp Error: 	... 8 more
STATUS | wrapper  | 2016/10/03 12:32:02 | <-- Wrapper Stopped

> 


ç
can you helpme.

tks

pd: sorry for my english

**Comment by tananaev** [comment]
@federicobalm, you are missing some libraries. I guess you are not using right version of the server.
