### ISSUE TITLE
WARNING: Unable to find permissions manager

### ISSUE THREAD

**Issue by johansid** [tananaev/traccar#1756]
Hai Anton,

On my wrapper log I got repeated message:
```
INFO   | jvm 1    | 2016/02/27 08:00:53 | Feb 27, 2016 8:00:53 AM org.traccar.web.server.model.BackendRefresher refreshWithReflection
INFO   | jvm 1    | 2016/02/27 08:00:53 | WARNING: Unable to find permissions manager
INFO   | jvm 1    | 2016/02/27 08:14:27 | Feb 27, 2016 8:14:27 AM org.traccar.web.server.model.BackendRefresher refreshWithReflection
INFO   | jvm 1    | 2016/02/27 08:14:27 | WARNING: Unable to find permissions manager
```
**below another logs before above message:**
```
INFO   | jvm 1    | 2016/02/27 07:54:54 | [qtp1741615821-39] WARN / - Key[type=org.traccar.web.server.model.RESTApiServlet, annotation=[none]]: Error during method 'login' call: null
INFO   | jvm 1    | 2016/02/27 07:54:54 | java.lang.reflect.InvocationTargetException
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.traccar.web.server.model.RESTApiServlet.makeRestCall(RESTApiServlet.java:110)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.traccar.web.server.model.RESTApiServlet.doPost(RESTApiServlet.java:63)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/02/27 07:54:54 | Caused by: java.lang.IllegalStateException
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:111)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.traccar.web.server.model.MethodCallLogger.invoke(MethodCallLogger.java:43)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:58)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:156)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/02/27 07:54:54 | 	... 43 more
INFO   | jvm 1    | 2016/02/27 07:55:14 | Feb 27, 2016 7:55:14 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2016/02/27 07:55:14 | INFO: Login 'abimanyu'
INFO   | jvm 1    | 2016/02/27 07:55:14 | [qtp1741615821-36] WARN / - Key[type=org.traccar.web.server.model.RESTApiServlet, annotation=[none]]: Error during method 'login' call: null
INFO   | jvm 1    | 2016/02/27 07:55:14 | java.lang.reflect.InvocationTargetException
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.traccar.web.server.model.RESTApiServlet.makeRestCall(RESTApiServlet.java:110)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.traccar.web.server.model.RESTApiServlet.doPost(RESTApiServlet.java:63)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/02/27 07:55:14 | Caused by: java.lang.IllegalStateException
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:111)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.traccar.web.server.model.MethodCallLogger.invoke(MethodCallLogger.java:43)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:58)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:156)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/02/27 07:55:14 | 	... 43 more
```

**Comment by tananaev** [comment]
What version of the web interface are you using?

**Comment by johansid** [comment]
I used server 3.3 and web using vitalidze

-----Original Message-----

**Comment by tananaev** [comment]
The issue is in the web UI mod (possibly config). @vitalidze should be able to help with the problem.

**Comment by johansid** [comment]
This issue occurs since i change mod web in 3.3
I try use config 3.2 with mod web, problem permission gone but still any errors in java.


-----Original Message-----

**Comment by vitalidze** [comment]
These warnings can be safely ignored.

Error is not related with them anyhow, it shows login attempt with incorrect credentials (wrong username or password)
