### ISSUE TITLE
Errors in traccar/logs/wrapper.log.xxxxxxxx

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1797]
hi,

Was just having a look at the logs in the traccar/logs directory. I saw these lines in the file called wrapper.log.20160318. Any idea as to whether these would cause any problems?

```
STATUS | wrapper  | 2016/03/18 05:15:03 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/03/18 05:15:03 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/03/18 05:15:03 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/03/18 05:15:03 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/03/18 05:15:03 | 
STATUS | wrapper  | 2016/03/18 05:15:03 | Launching a JVM...
INFO   | jvm 1    | 2016/03/18 05:15:03 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/03/18 05:15:04 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/03/18 05:15:04 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/03/18 05:15:04 | INFO 3/18/16 5:15 AM: liquibase: Clearing database change log checksums
INFO   | jvm 1    | 2016/03/18 05:15:04 | INFO 3/18/16 5:15 AM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/03/18 05:15:04 | INFO 3/18/16 5:15 AM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/03/18 05:15:04 | INFO 3/18/16 5:15 AM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/03/18 05:15:05 | INFO 3/18/16 5:15 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2016/03/18 05:15:05 | INFO 3/18/16 5:15 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2016/03/18 05:15:05 | INFO 3/18/16 5:15 AM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/03/18 05:15:05 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kflt9f11ry4vy1bzrx7l|5f9f652e, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kflt9f11ry4vy1bzrx7l|5f9f652e, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2016/03/18 05:15:05 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @2387ms
INFO   | jvm 1    | 2016/03/18 05:15:06 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.15.v20160210
INFO   | jvm 1    | 2016/03/18 05:15:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6fb8f5ab{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/03/18 05:15:07 | [WrapperSimpleAppMain] WARN org.eclipse.jetty.server.handler.AbstractHandler - No Server set for org.traccar.web.WebServer$1@689a744
INFO   | jvm 1    | 2016/03/18 05:15:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@20515521{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/03/18 05:15:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @3440ms
INFO   | jvm 1    | 2016/03/18 05:15:07 | [qtp1651790252-59] WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket
INFO   | jvm 1    | 2016/03/18 05:15:07 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.traccar.api.AsyncSocketServlet$1.createWebSocket(AsyncSocketServlet.java:36)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:166)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:153)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:151)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/03/18 05:15:07 | 	at java.lang.Thread.run(Thread.java:745)
...
INFO   | jvm 1    | 2016/03/18 05:15:12 | [qtp1651790252-60] WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket
INFO   | jvm 1    | 2016/03/18 05:15:12 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.traccar.api.AsyncSocketServlet$1.createWebSocket(AsyncSocketServlet.java:36)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:166)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:153)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:151)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/03/18 05:15:12 | 	at java.lang.Thread.run(Thread.java:745)
```

The other log file trackers-server.log does not indicate any problems

```
2016-03-18 05:15:04  INFO: Operating system name: Linux version: 4.5.0-x86_64-linode65 architecture: amd64
2016-03-18 05:15:04  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.74-b02
2016-03-18 05:15:04  INFO: Memory limit heap: 878mb non-heap: 0mb
2016-03-18 05:15:04  INFO: Character encoding: UTF-8 charset: UTF-8
2016-03-18 05:15:04  INFO: Version: 3.4-SNAPSHOT
2016-03-18 05:15:06  INFO: Starting server...
```

**Comment by m-menon** [comment]
After some experimenting I think I may have found the reason. It seems to occur if I have the browser open / traccar website and then start / restart traccar server. Probably the web socket trying to send some request, or is it trying to reconnect or something when the traccar server is not ready?

To reproduce: 1) Open Traccar website

**Comment by tananaev** [comment]
When you restart server you lose user session, so when browser tries to request data from server, it fails with this error.

**Comment by m-menon** [comment]
alrite...thanks :-)
