### ISSUE TITLE
Does forward.url get written to log

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1813]
I am unable to get forward.url to work. Does it write to a log or something so that I can see if it is being called? Thanks

**Comment by tananaev** [comment]
No, it doesn't have any logging.

**Comment by m-menon** [comment]
Strange, my forward url doesn't get called. I have just put a link to a page which when called writes a record to the database. If I open the page or refresh it directly in the browser, the record gets added indicating that the page is working fine but when I put the exact same URL in the forward.url and enable forward url, nothing happens. It just doesn't seem to be calling the URL. Any clues?

**Comment by tananaev** [comment]
No ideas. I guess you need to debug the problem. Possibly add some logging.

**Comment by m-menon** [comment]
Logically it can just be a html page that I can call even without any query parameters I guess?

**Comment by tananaev** [comment]
Yes, it can just be a URL without any parameters.

**Comment by m-menon** [comment]
really strange cos I tried calling the plain url with no parameters from different browsers and all work but absolutely nothing happens when I put the same thing in the configuration file. I hope nothing is wrong with these 2 lines from what I can see

```
    <entry key='forward.enable'>true</entry>
    <entry key='forward.url'>https://trackerdata1.clouddb.com/simplepage.html</entry>
```

**Comment by tananaev** [comment]
The URL is not accessible, but the format is correct in general.

**Comment by m-menon** [comment]
oh that's because I changed the URL a bit before posting as it is used for other purposes too. My actual code has the working URL. Now I am trying to put that page on a different server and see the result

**Comment by m-menon** [comment]
And also I should just be able to throw in a html page in the opt/traccar/web folder and call that in the forward URL isn't it? Just curious...I know very little about java/jetty etc

**Comment by tananaev** [comment]
Here is an easy way to test it:
```
    <entry key='forward.enable'>true</entry>
    <entry key='forward.url'>http://localhost:5055/?id={uniqueId}</entry>
```

**Comment by m-menon** [comment]
Cool so I just enable     `<entry key='osmand.port'>5055</entry>`
, change my forward URL to `http://localhost:5055/?id={uniqueId}` and see if it gets logged. Thanks :+1:

**Comment by tananaev** [comment]
Yes, you should be able to see forwarded data in the log as HEX messages.

**Comment by m-menon** [comment]
excellent thanks

**Comment by m-menon** [comment]
Just curious about the semicolons in the forward url

`http://example.com:8080/gprmc/Data?id={uniqueId}&amp;code=0x0000&amp;gprmc={gprmc}`

And also do you have an example of a real forward url with all the parameters substituted for real values? I am almost there but I still have a bit of difficulty to make forward url work correctly. I am calling a Server side script to transform some the params and post to NoSQL db

Thanks
M.M

**Comment by m-menon** [comment]
I figured that out. Seems to work well now. Thanks anyways :-)

**Comment by evallgar** [comment]
@m-menon Could you please share how u figured out? Im trying to do similar but still having bi of difficulty to make forward work. With example code traccar server doesnt even start. Thanks

**Comment by tananaev** [comment]
It should start, as long as your config file is a valid XML. If something doesn't work, you should check logs for errors.

**Comment by evallgar** [comment]
It doesn't starts when `conf/default.xml` server config section looks like this
```

<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!-- SERVER CONFIG -->

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>./web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>./logs/tracker-server.log</entry>

    <entry key='event.forward.enable'>true</entry>
    <entry key='event.forward.url'>http://domain.tld/api/events</entry>
    <entry key='forward.enable'>true</entry>
    <entry key='forward.url'>http://domain.tld/api/positions?id={uniqueId}&deviceId={deviceId}&valid={valid}&fixTime={fixTime}&deviceTime={deviceTime}&protocol={protocol}&name={name}&latitude={latitude}&longitude={longitude}&altitude={altitude}&speed={speed}&course={course}&statusCode={statusCode}&address={address}&gprmc={gprmc}&attributes={attributes}</entry>
    <entry key='event.enable'>true</entry>
    <entry key='event.overspeedHandler'>true</entry>
    <entry key='event.overspeed.notRepeat'>true</entry>
    <entry key='event.motionHandler'>true</entry>
    <entry key='event.geofenceHandler'>true</entry>
    <entry key='event.alertHandler'>true</entry>
    <entry key='event.ignitionHandler'>true</entry>
    <entry key='event.statusHandler'>true</entry>
    <entry key='event.maintenanceHandler'>true</entry>
```


and `logs/wrapper.log20170328` reports:

```
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|21936/0|Service traccar|17-03-28 22:39:47|Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 82; The reference to entity "deviceId" must end with the ';' delimiter.
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at java.util.Properties$XmlSupport.load(Properties.java:1201)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at java.util.Properties.loadFromXML(Properties.java:881)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at org.traccar.Config.load(Config.java:37)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at org.traccar.Context.init(Context.java:186)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at org.traccar.Main.main(Main.java:35)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	... 6 more
INFO|21936/0|Service traccar|17-03-28 22:39:47|Caused by: org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 82; The reference to entity "deviceId" must end with the ';' delimiter.
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(XMLDocumentFragmentScannerImpl.java:1850)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3061)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
INFO|21936/0|Service traccar|17-03-28 22:39:47|	... 11 more
INFO|wrapper|Service traccar|17-03-28 22:39:47|waitpid 21936 59136
INFO|wrapper|Service traccar|17-03-28 22:39:47|exit code posix process: 59136 application: 0

```

Instead, if I change in `conf/default.xml` file this:

```
<entry key='forward.url'>http://domain.tld/api/positions?id={uniqueId}&deviceId={deviceId}&valid={valid}&fixTime={fixTime}&deviceTime={deviceTime}&protocol={protocol}&name={name}&latitude={latitude}&longitude={longitude}&altitude={altitude}&speed={speed}&course={course}&statusCode={statusCode}&address={address}&gprmc={gprmc}&attributes={attributes}</entry>
```

for this: (note: `&amp;` instead of `&`)

```
<entry key='forward.url'>http://domain.tld/api/positions?id={uniqueId}&amp;deviceId={deviceId}&amp;valid={valid}&amp;fixTime={fixTime}&amp;deviceTime={deviceTime}&amp;protocol={protocol}&amp;name={name}&amp;latitude={latitude}&amp;longitude={longitude}&amp;altitude={altitude}&amp;speed={speed}&amp;course={course}&amp;statusCode={statusCode}&amp;address={address}&amp;gprmc={gprmc}&amp;attributes={attributes}</entry>
```

Now `logs/wrapper.log20170328` ends with:

```
INFO|wrapper|Service traccar|17-03-28 22:54:42|posix_spawn pid 22495
INFO|wrapper|Service traccar|17-03-28 22:54:42|started process 22495
INFO|wrapper|Service traccar|17-03-28 22:54:42|started process with pid 22495
INFO|22495/0|Service traccar|17-03-28 22:54:44|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|22495/0|Service traccar|17-03-28 22:54:46|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|22495/0|Service traccar|17-03-28 22:54:46|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO|22495/0|Service traccar|17-03-28 22:54:47|INFO 3/28/17 10:54 PM: liquibase: Clearing database change log checksums
INFO|22495/0|Service traccar|17-03-28 22:54:47|INFO 3/28/17 10:54 PM: liquibase: Successfully acquired change log lock
INFO|22495/0|Service traccar|17-03-28 22:54:47|INFO 3/28/17 10:54 PM: liquibase: Successfully released change log lock
INFO|22495/0|Service traccar|17-03-28 22:54:47|INFO 3/28/17 10:54 PM: liquibase: Successfully acquired change log lock
INFO|22495/0|Service traccar|17-03-28 22:54:50|INFO 3/28/17 10:54 PM: liquibase: Reading from gregorgps.DATABASECHANGELOG
INFO|22495/0|Service traccar|17-03-28 22:54:50|INFO 3/28/17 10:54 PM: liquibase: Reading from gregorgps.DATABASECHANGELOG
INFO|22495/0|Service traccar|17-03-28 22:54:50|INFO 3/28/17 10:54 PM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Can't DROP 'uk_user_token'; check that column/key exists [Failed SQL: ALTER TABLE gregorgps.users DROP KEY uk_user_token]
INFO|22495/0|Service traccar|17-03-28 22:54:50|INFO 3/28/17 10:54 PM: liquibase: Successfully released change log lock
INFO|22495/0|Service traccar|17-03-28 22:54:51|[main] INFO org.eclipse.jetty.util.log - Logging initialized @7863ms
INFO|22495/0|Service traccar|17-03-28 22:54:52|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.21.v20170120
INFO|22495/0|Service traccar|17-03-28 22:54:54|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@67022ea{/api,null,AVAILABLE}
INFO|22495/0|Service traccar|17-03-28 22:54:54|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@43a5b00b{HTTP/1.1}{0.0.0.0:8082}
INFO|22495/0|Service traccar|17-03-28 22:54:54|[main] INFO org.eclipse.jetty.server.Server - Started @11411ms
```

However, today's `logs/tracker-server.log.20170328` file does not even exists, yesterday's file does.

So far, my API Endpoint (positions) has not registered any activity at all.

**Comment by evallgar** [comment]
I'm actually using postman to test my api endpoint successfully.

Postman uses this:

```
POST /api/positions HTTP/1.1
Host: domain.tld
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: dda24dba-bee4-3378-71a5-c6e8c4c0857d

id=3&deviceId=3&valid=true&fixTime=2017-03-27 04:00:06&deviceTime=2017-03-27 04:00:00&protocol=gps103&name=Test Device&latitude=23.68438666666667&longitude=-99.18282833333333&altitude=0&speed=0&course=0&statusCode=0&address=2238 North Drive, Brownsville, TX., USA&gprmc=&attributes={"ip":"201.144.174.16","distance":0.0,"totalDistance":1.106864443E7}

```

**Comment by tananaev** [comment]
Today's `tracker-server.log` file doesn't have a date suffix.

**Comment by evallgar** [comment]
Sorry for the misunderstanding.

Contents of `tracker-server.log` looks ok. Unless of course I'm not getting it right again.

```
2017-03-29 01:07:12  INFO: [149102A4] id: 459710040266125, time: 2017-03-29 01:07:06, lat: 25.68429, lon: -100.18291, speed: 0.0, course: 0.0
2017-03-29 01:07:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:07:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:08:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:08:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:09:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:09:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:10:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:10:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:11:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:11:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:12:12 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 696d65693a3435393731303034303236363132352c747261636b65722c3137303332393039313230392c2c462c3031313230362e3030302c412c323534312e303537352c4e2c31303031302e393734342c572c302e30302c303b
2017-03-29 01:12:18  INFO: [149102A4] id: 459710040266125, time: 2017-03-29 01:12:06, lat: 25.68429, lon: -100.18291, speed: 0.0, course: 0.0
2017-03-29 01:12:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:12:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:13:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:13:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:14:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:14:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:15:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:15:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:16:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:16:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:17:11 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 696d65693a3435393731303034303236363132352c747261636b65722c3137303332393039313730392c2c462c3031313730352e3030302c412c323534312e303537352c4e2c31303031302e393734342c572c302e30302c303b
2017-03-29 01:17:12  INFO: [149102A4] id: 459710040266125, time: 2017-03-29 01:17:05, lat: 25.68429, lon: -100.18291, speed: 0.0, course: 0.0
2017-03-29 01:17:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:17:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:18:59 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:18:59 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:19:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:19:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:20:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:20:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:21:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:21:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:22:11 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 696d65693a3435393731303034303236363132352c747261636b65722c3137303332393039323230392c2c462c3031323230352e3030302c412c323534312e303537352c4e2c31303031302e393734342c572c302e30302c303b
2017-03-29 01:22:12  INFO: [149102A4] id: 459710040266125, time: 2017-03-29 01:22:05, lat: 25.68429, lon: -100.18291, speed: 0.0, course: 0.0
2017-03-29 01:22:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:22:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:23:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:23:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
2017-03-29 01:24:58 DEBUG: [149102A4: 5001 < 201.144.174.82] HEX: 3435393731303034303236363132353b
2017-03-29 01:24:58 DEBUG: [149102A4: 5001 > 201.144.174.82] HEX: 4f4e
```

What could it be the reason my API Endpoint is not being invoked?

**Comment by m-menon** [comment]
@evallgar Did you try replacing the url with something simpler just to test whether it (forward url) is being called? You could check the logs on either side ( the server where you are forwarding the requests to ) or the traccar logs ( I am not sure though whether traccar logs forward requests in the log but I 'think' it does )

So you could simply take out the existing URL with all those params, and just a simple url with something like http://domain.tld/api/test ( You could create a simple endpoint like this for testing ... that perhaps just logs the requests ) ... and you could then go on adding the params and see where it breaks (if it does).

**Comment by evallgar** [comment]
Thanks @m-menon for your reply. My actual endpoints are for testing purposes. Both are logging whatever happens.

But What I have not tried yet is a more simpler forward url. Will try it right now.

Im also trying to take positions to a mongodb which I understand, you are also onto something like that. How did it go to you?

**Comment by m-menon** [comment]
As these are GET requests (it wasn't POST when I looked at it the last time), you could simply have an endpoint that just returns a HTTP 200 and then try that endpoint using a browser on that very machine  ( where traccar server is installed ) and see if it's accessible and returns an OK status.

Yes I did manage to get the positions to go into MongoDB. Depending on the language you are familiar with and are currently using, lots of REST API frameworks out there.  If you using a hosted MongoDB service like [mLab](http://docs.mlab.com/data-api/) then you could simply use their REST APIs - can be done in a jiffy. But they do mention this though

> The second method, documented in this article, is to connect via mLab’s RESTful Data API. Use this method only if you cannot connect using a MongoDB driver

**Comment by evallgar** [comment]
@m-menon 

> As these are GET requests (it wasn't POST when I looked at it the last time), you could simply have an endpoint that just returns a HTTP 200 and then try that endpoint using a browser on that very machine ( where traccar server is installed ) and see if it's accessible and returns an OK status.

What do you mean?
