### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1849]
hi,

If I were to switch to MariaDB, what configuration would need to be changed? I am already running traccar on MySQL. 

Thanks,
M.M

**Comment by tananaev** [comment]
I guess just the connection config if it's different from MySQL.

**Comment by m-menon** [comment]
alright. Are you aware of any working config of Traccar with MariaDB. If yes will you be able to share the connection parameters with me. Thanks

**Comment by tananaev** [comment]
Have you tried to search the answer?

**Comment by m-menon** [comment]
yes, I did. I found this

```
In traccar.cfg you need to change the database config to:
<entry key='database.driver'>org.mariadb.jdbc.Driver</entry>
<entry key='database.dataSource'>org.mariadb.jdbc.MySQLDataSource</entry>

Additionally I had to add the MariaDB jdbc to the classpath in the wrapper.cfg file:
wrapper.java.classpath.3=/usr/share/java/mariadb-jdbc/mariadb-java-client.jar
```

but I am not too sure whether it's still relevant. And moreover the last line speaks of adding the classpath in wrapper.cfg... is that required?

Thanks

**Comment by tananaev** [comment]
I have never tried it myself, so I don't know the answer. 

Instead of adding classpath in wrapper, you can use following config parameter:
```
<entry key='database.driverFile'>/usr/share/java/mariadb-jdbc/mariadb-java-client.jar</entry>
```

**Comment by khfrabbi** [comment]
I am using mariadb without any problem following intructions from https://www.traccar.org/mysql/

Installed Packages
Name      : mariadb
Arch        : x86_64
Epoch     : 1
Version   : 5.5.47
Release  : 1.el7_2

**Comment by m-menon** [comment]
I managed to get it to work with MariaDB using it's own connector. It all starts up fine and there are no errors in the log and the data is reaching the server, But I noticed something just turn up in the log file

```
INFO   | jvm 1    | 2016/04/03 21:12:17 | java.sql.SQLWarning: Out of range value for column 'devicetime' at row 1
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at org.mariadb.jdbc.MariaDbConnection.getWarnings(MariaDbConnection.java:836)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.c3p0.impl.NewProxyConnection.getWarnings(NewProxyConnection.java:933)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.c3p0.SQLWarnings.logAndClearWarnings(SQLWarnings.java:54)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckin(C3P0PooledConnectionPool.java:399)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckin(BasicResourcePool.java:1760)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.resourcepool.BasicResourcePool.access$200(BasicResourcePool.java:44)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.resourcepool.BasicResourcePool$1RefurbishCheckinResourceTask.run(BasicResourcePool.java:1378)
INFO   | jvm 1    | 2016/04/03 21:12:17 | 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
INFO   | jvm 1    | 2016/04/03 21:12:17 | [C3P0PooledConnectionPoolManager[identityToken->z8kfsx9f1pkgf6j1i41l84|58e8e8d]-HelperThread-#2] INFO com.mchange.v2.c3p0.SQLWarnings - Out of range value for column 'fixtime' at row 1
```

Thanks,
M.M

**Comment by m-menon** [comment]
Just did a describe table and the structure is:

```
MariaDB [trackerdata0001]> describe positions;
+------------+---------------+------+-----+---------------------+-----------------------------+
| Field      | Type          | Null | Key | Default             | Extra                       |
+------------+---------------+------+-----+---------------------+-----------------------------+
| id         | int(11)       | NO   | PRI | NULL                | auto_increment              |
| protocol   | varchar(128)  | YES  |     | NULL                |                             |
| deviceid   | int(11)       | NO   | MUL | NULL                |                             |
| servertime | timestamp     | NO   |     | CURRENT_TIMESTAMP   | on update CURRENT_TIMESTAMP |
| devicetime | timestamp     | NO   |     | 0000-00-00 00:00:00 |                             |
| fixtime    | timestamp     | NO   |     | 0000-00-00 00:00:00 |                             |
| valid      | bit(1)        | NO   |     | NULL                |                             |
| latitude   | double        | NO   |     | NULL                |                             |
| longitude  | double        | NO   |     | NULL                |                             |
| altitude   | float         | NO   |     | NULL                |                             |
| speed      | float         | NO   |     | NULL                |                             |
| course     | float         | NO   |     | NULL                |                             |
| address    | varchar(512)  | YES  |     | NULL                |                             |
| attributes | varchar(4096) | NO   |     | NULL                |                             |
+------------+---------------+------+-----+---------------------+-----------------------------+
14 rows in set (0.00 sec)
```

**Comment by tananaev** [comment]
Possibly it tries to insert 0 timestamp value which is not valid.

**Comment by m-menon** [comment]
But it never happened with MySQL, and that's a bit puzzling.

**Comment by m-menon** [comment]
I don't have the error so far after I added another parameters in the JDBC connection string: `zeroDateTimeBehavior=convertToNull`

My MariaDB connection parameters which seems to work well so far, in case anyone finds this useful
```
    <entry key='database.driver'>org.mariadb.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mariadb://127.0.0.1:3306/trackerdata?allowMultiQueries=true&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.driverFile'>/usr/share/java/mariadb-java-client-1.4.0.jar</entry>
    <entry key='database.user'>mydbuser</entry>
    <entry key='database.password'>mydbpwd</entry>
```

I have used the version 10.1 of MariaDB downloaded from here:
https://downloads.mariadb.org/mariadb/repositories/#mirror=nus&distro=Ubuntu&distro_release=trusty--ubuntu_trusty&version=10.1

With the connector from the below link
https://mariadb.com/my_portal/download/java-client
