### ISSUE TITLE
Trouble converting to mysqldb

### ISSUE THREAD

**Issue by ifindu-dk** [tananaev/traccar#2049]
```
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'><![CDATA[jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES]]</entry>
 <entry key='database.user'>xxxxxx</entry> 
 <entry key='database.password'>YYYYYYyyyyy</entry>
```
This is the different lines, when I shall connect to mysql.
I have created the DB with the correct name.

Bot the serbice won't start, and comes with no specific error, i get a system_error_code 1066 that say service has returned service-specifik error, but I don't find any......

Is it an typeerror in the jdbc?

Here is the servers logfile:
```
STATUS | wrapper  | 2016/06/25 00:21:37 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/06/25 00:21:37 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/06/25 00:21:37 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/06/25 00:21:37 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/06/25 00:21:37 | 
STATUS | wrapper  | 2016/06/25 00:21:38 | Launching a JVM...
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 298; columnNumber: 16; XML document structures must start and end within the same entity.
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at sun.util.xml.PlatformXmlPropertiesProvider.load(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at java.util.Properties$XmlSupport.load(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at org.traccar.Config.load(Config.java:29)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:112)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 298; columnNumber: 16; XML document structures must start and end within the same entity.
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(Unknown Source)
INFO   | jvm 1    | 2016/06/25 00:21:38 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2016/06/25 00:21:41 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Your XML is invalid. What is this:
```
<entry key='database.url'><![CDATA[jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES]]</entry>
```

Where did you get this line from?

**Comment by ifindu-dk** [comment]
Because the original gives error, with something ala expect ; after bla bla.
then someone wrote that i could put it in CDATA
and that error disapeared

**Comment by tananaev** [comment]
That's definitely incorrect format. Please follow exact instructions from the official website. If it doesn't work, post the errors here.

**Comment by ifindu-dk** [comment]
<entry key='database.url'><![CDATA[jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES]]**>**</entry>

Thnx for the great eyes....
the > in the end - did the trick - i had forgotten to end the CDATA
Now it's working
