### ISSUE TITLE
Web server stop responding

### ISSUE THREAD

**Issue by vladamirk** [tananaev/traccar#2200]
Hi Anton, below you can see a part of log file (wrapper.log) that getting spammed and grow so big that take over all space on HD 100% and it stop working obviously, it's happened before few times but we didn't pay attention to it, but now it's happening more often, if you can see solution for this problem please let me know, thank you in advance. Hope to hear from you soon.

```
INFO   | jvm 1    | 2016/08/09 17:57:26 | [qtp1608143191-33-acceptor-0@434dd261-ServerConnector@343af33e{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
INFO   | jvm 1    | 2016/08/09 17:57:26 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/08/09 17:57:26 | [qtp1608143191-33-acceptor-0@434dd261-ServerConnector@343af33e{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
INFO   | jvm 1    | 2016/08/09 17:57:26 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/08/09 17:57:26 | [qtp1608143191-33-acceptor-0@434dd261-ServerConnector@343af33e{HTTP/1.1}{0.0.0.0:8082}] WARN org.eclipse.jetty.server.ServerConnector -
INFO   | jvm 1    | 2016/08/09 17:57:26 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/08/09 17:57:26 |       at java.lang.Thread.run(Thread.java:745)
```

**Comment by tananaev** [comment]
You have too many open connections. You need to increase the OS limit on number of open files and set connection timeout in Traccar. This issue has been discussed multiple times on GitHub.

**Comment by vladamirk** [comment]
Thank you for your fast respond.
