### ISSUE TITLE
NullReferenceException after password change

### ISSUE THREAD

**Issue by jorrit** [tananaev/traccar#2235]
WHen I change my password via the web admin interface the interface doesn't force me to relogin nor does it update my session with the new password. The subsequent WebSocket requests fail with an authentication error, creating a non-responsive UI.

On the server side, each WebSocket connection attempt results in the following error:

```
[qtp1317394-28] WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket
java.lang.NullPointerException
        at org.traccar.api.AsyncSocketServlet$1.createWebSocket(AsyncSocketServlet.java:37)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:166)
        at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:153)
        at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:151)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tananaev** [comment]
Works fine for me. Session doesn't have user password, so there shouldn't be any problem. Are you sure you are using official version without any modifications?

**Comment by jorrit** [comment]
Yes, 3.6 on MySQL. If I have time this week I will try to reproduce with a clean database.

**Comment by jorrit** [comment]
I can't reproduce it.

**Comment by rahmanshu** [comment]
traccar very slow
