### ISSUE TITLE
Data truncation: Truncated incorrect DOUBLE value: 'hagvat' -  error

### ISSUE THREAD

**Issue by himsashu** [tananaev/traccar#2294]
Dear Sir
I have installed Traccar version 3.5	on my PC and configured this with OpenGTS. For some days, it was OK but suddenly 2 days back, I am getting below error. No data getting saved on mysql.

**2016-09-07 12:37:25  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:25  INFO: [BC844F2D] id: 352848023053297, time: 2016-09-07 12:37:00, lat: 19.11121, lon: 72.83603, speed: 0.0, course: 72.0**

The log is as below:

2016-09-07 12:37:23 DEBUG: [C2FB8380: 5069 < 223.176.160.72] HEX: 24312c31323335382c30372c30392c31362c30372c30362c34362c32383430393431384e2c303737303234373836452c3033342e332c39322c39393931322c312c302c302c312c4123
2016-09-07 12:37:25  INFO: [EFE46D15] connected
2016-09-07 12:37:25 DEBUG: [BC844F2D: 5027 < 1.39.26.53] HEX: 000000000000002b0801000001570378a447002b69e5800b642390002400480900000004020100b300024231434309e300000100004244
2016-09-07 12:37:25 DEBUG: [BC844F2D: 5027 > 1.39.26.53] HEX: 00000001
2016-09-07 12:37:25  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:25  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:25  INFO: [BC844F2D] id: 352848023053297, time: 2016-09-07 12:37:00, lat: 19.11121, lon: 72.83603, speed: 0.0, course: 72.0
2016-09-07 12:37:26  INFO: [C2FB8380] disconnected
2016-09-07 12:37:27 DEBUG: [EFE46D15: 5027 < 106.202.161.198] HEX: 000f333536333037303432383239373230
2016-09-07 12:37:27 DEBUG: [EFE46D15: 5027 > 106.202.161.198] HEX: 01
2016-09-07 12:37:27  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:29 DEBUG: [BCDB0B2E: 5023 < 1.39.24.22] HEX: 78780d010358735070166177001993a90d0a
2016-09-07 12:37:29  WARN: Unknown device - 358735070166177 (1.39.24.22)
2016-09-07 12:37:29 DEBUG: [EFE46D15: 5027 < 106.202.161.198] HEX: 00000000000000af080400000157037729e0002e1c55801108bc8000cc0000090000000504010002000300f0000001c700000000000000015703781440002e1c55801108bc8000d10000090000000504010002000300f0000001c70000000000000001570378a8b0002e1c55801108bc8000d10000090000000504010002000300f0010001c70000000000000001570378e348002e1c55801108bc8000d10000090000000504010002000300f0010001c70000000000040000fe4b
2016-09-07 12:37:29 DEBUG: [EFE46D15: 5027 > 106.202.161.198] HEX: 00000004
2016-09-07 12:37:29  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:29  INFO: [32828F02] connected
2016-09-07 12:37:29  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:29  INFO: [EFE46D15] id: 356307042829720, time: 2016-09-07 12:37:01, lat: 28.57852, lon: 77.36088, speed: 0.0, course: 0.0
2016-09-07 12:37:29  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:29  INFO: [EFE46D15] id: 356307042829720, time: 2016-09-07 12:36:23, lat: 28.57852, lon: 77.36088, speed: 0.0, course: 0.0
2016-09-07 12:37:29  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:29  INFO: [EFE46D15] id: 356307042829720, time: 2016-09-07 12:37:16, lat: 28.57852, lon: 77.36088, speed: 0.0, course: 0.0
2016-09-07 12:37:29  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:29  INFO: [EFE46D15] id: 356307042829720, time: 2016-09-07 12:35:23, lat: 28.57852, lon: 77.36088, speed: 0.0, course: 0.0
2016-09-07 12:37:30 DEBUG: [60AB5C61: 5069 < 223.176.183.37] HEX: 24312c31323339362c30372c30392c31362c30372c30372c31362c32383431313438324e2c303737323436383739452c30302e302c3131372c39303734362c302c302c302c312c4123
2016-09-07 12:37:31 DEBUG: [4C4C685E: 5069 < 1.39.25.86] HEX: 24312c31323530342c30372c30392c31362c30372c30372c30332c31393436383630374e2c303732343732363031452c30302e302c3331312c3133362c4123
2016-09-07 12:37:32 DEBUG: [32828F02: 5027 < 1.39.25.22] HEX: 000f333532383438303234323534363730
2016-09-07 12:37:32 DEBUG: [32828F02: 5027 > 1.39.25.22] HEX: 01
2016-09-07 12:37:32  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:34  INFO: [60AB5C61] disconnected
2016-09-07 12:37:35  INFO: [BC844F2D] disconnected
2016-09-07 12:37:35  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:36 DEBUG: [32828F02: 5027 < 1.39.25.22] HEX: 000000000000002b080100000157037888c7002b6e49c00b727390001f00dc0a001d0004020101b3000242371043045700000100001885
2016-09-07 12:37:36 DEBUG: [32828F02: 5027 > 1.39.25.22] HEX: 00000001
2016-09-07 12:37:36  INFO: Query not provided: database.updateDeviceStatus
2016-09-07 12:37:36  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-09-07 12:37:36  INFO: [32828F02] id: 352848024254670, time: 2016-09-07 12:36:53, lat: 19.20501, lon: 72.86481, speed: 15.7, course: 220.0

**Comment by tananaev** [comment]
What's "hagvat"? What config are you using?

**Comment by himsashu** [comment]
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>
	
	<entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'></entry>
	
    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/gts?allowMultiQueries=true</entry>
    <entry key='database.user'></entry>
    <entry key='database.password'></entry>

    <entry key='database.selectDevicesAll'>
        SELECT imeiNumber AS id, imeiNumber AS uniqueID FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
    </entry>

    <entry key='database.insertPosition'>
        START TRANSACTION;
            SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = :device_id;
            SELECT @distance := ((ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitude * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180) * COS((@lastLongitude - :longitude) * PI() / 180)) * 180 / PI()) * 60 * 1.852);
			UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastOdometerKM = (@odometer + @distance), lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastTotalConnectTime = UNIX_TIMESTAMP(NOW()), lastUpdateTime = UNIX_TIMESTAMP(NOW()), deviceCode = 'car' WHERE imeiNumber = :device_id;
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
			INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed, :course, :altitude, '', @distance, (@odometer + @distance), UNIX_TIMESTAMP(NOW()), :address);
        COMMIT;
    </entry>

**Comment by tananaev** [comment]
Not sure what's wrong there. I would recommend to try removing/replacing some parts of queries and see which part causes this error.

**Comment by himsashu** [comment]
Hi Tananaev
I have tried everything permutation and combination but problem still persist. I am using 3.4 version from last 4 or 5 months and Traccar was working really well. This problem started just few days back.
The log file is as below:

2016-09-09 07:07:08  INFO: Operating system name: Linux version: 3.13.0-57-generic architecture: amd64
2016-09-09 07:07:08  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
2016-09-09 07:07:08  INFO: Memory limit heap: 880mb non-heap: 214mb
2016-09-09 07:07:08  INFO: Character encoding: UTF-8 charset: UTF-8
2016-09-09 07:07:08  INFO: Version: 3.4-SNAPSHOT
2016-09-09 07:07:09  INFO: Query not provided: database.selectLatestPositions
2016-09-09 07:07:10  INFO: Starting server...
2016-09-09 07:07:11  INFO: [625A1967] connected
2016-09-09 07:07:12  INFO: [2E0CC3A8] connected
2016-09-09 07:07:12 DEBUG: [2E0CC3A8: 5023 < 1.39.27.69] HEX: 78780d01035873507009786900006f190d0a
2016-09-09 07:07:13  INFO: [6CEC345C] connected
2016-09-09 07:07:13  INFO: [9E2F2806] connected
2016-09-09 07:07:13 DEBUG: [6CEC345C: 5001 < 1.39.26.73] HEX: 23232c696d65693a3435393731303034303532373439322c413b
2016-09-09 07:07:13 DEBUG: [6CEC345C: 5001 > 1.39.26.73] HEX: 4c4f4144
2016-09-09 07:07:13 DEBUG: [625A1967: 5069 < 106.204.144.119] HEX: 24312c31323431382c30392c30392c31362c30372c30362c31342c32383431313331304e2c303737303534393430452c3030302e302c35342c35353832382c312c302c302c312c412324312c31323431382c30392c30392c31362c30362c34302c31372c32383431313331304e2c303737303534393430452c3030302e302c3134312c35353832382c312c302c302c312c4123
2016-09-09 07:07:14 DEBUG: [2E0CC3A8: 5023 > 1.39.27.69] HEX: 787805010000c8550d0a
2016-09-09 07:07:14  INFO: Query not provided: database.updateDeviceStatus
2016-09-09 07:07:14  INFO: Query not provided: database.updateDeviceStatus
2016-09-09 07:07:14 DEBUG: [9E2F2806: 5069 < 1.39.26.192] HEX: 24312c31323530342c30392c30392c31362c30312c33362c33372c31393436383631324e2c303732343732363534452c30302e302c33352c31382c412324312c31323530342c30392c30392c31362c30312c32302c33392c31393436383631324e2c303732343732363534452c30302e302c31332c31382c412324312c31323530342c30392c30392c31362c30312c32312c33392c31393436383631324e2c303732343732363534452c30302e302c31302c31382c4123
2016-09-09 07:07:14 DEBUG: [2E0CC3A8: 5023 < 1.39.27.69] HEX: 78780a13040601000200015c860d0a
2016-09-09 07:07:14 DEBUG: [2E0CC3A8: 5023 > 1.39.27.69] HEX: 787805130001e9f10d0a
2016-09-09 07:07:14  INFO: Query not provided: database.updateDeviceStatus
**2016-09-09 07:07:14  WARN: Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)**
2016-09-09 07:07:14  INFO: [2E0CC3A8] id: 358735070097869, time: 1970-01-01 05:30:00, lat: 0.00000, lon: 0.00000, speed: 0.0, course: 0.0

I don't what is means of **Data truncation: Truncated incorrect DOUBLE value: 'hagvat' - MysqlDataTruncation (... < QueryBuilder:431 < DataManager:306 < DefaultDataHandler:27 < ...)**




I tried to update the Traccar to 3.6. The default XML setting works well but when I configure it for OpenGTS then I am getting below error:

STATUS | wrapper  | 2016/09/09 06:50:25 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/09 06:50:25 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/09 06:50:25 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/09 06:50:25 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/09 06:50:25 | 
STATUS | wrapper  | 2016/09/09 06:50:25 | Launching a JVM...
INFO   | jvm 1    | 2016/09/09 06:50:26 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/09 06:50:27 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/09/09 06:50:27 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.Connection.getNetworkTimeout()I)
INFO   | jvm 1    | 2016/09/09 06:50:27 | [WrapperSimpleAppMain] ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (com.mysql.jdbc.Connection.isValid(I)Z)
INFO   | jvm 1    | 2016/09/09 06:50:27 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
INFO   | jvm 1    | 2016/09/09 06:50:27 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: com.mysql.jdbc.Connection.isValid(I)Z
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabase(DataManager.java:134)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:87)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:136)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:30)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: Caused by: java.lang.AbstractMethodError: com.mysql.jdbc.Connection.isValid(I)Z
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:375)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:350)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:321)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
INFO   | jvm 1    | 2016/09/09 06:50:27 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2016/09/09 06:50:30 | <-- Wrapper Stopped

I am completely clueless. Please help me.

**Comment by tananaev** [comment]
I don't believe that you tried all combinations. What if you try this:
```
    <entry key='database.insertPosition'>
        START TRANSACTION;
            SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = :device_id;
        COMMIT;
    </entry>
```

**Comment by himsashu** [comment]
Believe me, I have already tried but same error.

**Comment by himsashu** [comment]
Latest version of Standard Traccar works well but when I integrate with OpenGTS, it generates that error.

**Comment by tananaev** [comment]
I can check it for you if you provide access details.
