### ISSUE TITLE
Ubuntu 16.04. Traccar is not starting on system startup anymore

### ISSUE THREAD

**Issue by solvek** [tananaev/traccar#2298]
After I have upgraded my ubuntu to 16.04 traccar stopped to start automatically on startup. Seems init.d  system does not work by default on Ubuntu 16

**Comment by Abyss777** [comment]
Hello,
16.04 migrated to systemd, something could happen while upgrade.
Please try to enable service
````
sudo systemctl enable traccar.service
````
And start it
````
sudo systemctl start traccar.service
````

You can also read the following guidance https://www.digitalocean.com/community/tutorials/systemd-essentials-working-with-services-units-and-the-journal

**Comment by solvek** [comment]
Running 

`sudo systemctl enable traccar.service`

gets me this

```
traccar.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable traccar
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
The script you are attempting to invoke has been converted to an Upstart
job, but lsb-header is not supported for Upstart jobs.

```

**Comment by Abyss777** [comment]
Is symbolic link `/etc/init.d/traccar`exists and point to `/opt/traccar/bin/traccar` ?

**Comment by solvek** [comment]
Yes, it does exist

**Comment by Abyss777** [comment]
Just a suggestion, check if exists something connected to traccar in `/lib/init/ubstart-job` and remove it.
After that try to enable service again.

**Comment by tananaev** [comment]
Please try solution from this thread:

https://www.traccar.org/forums/topic/ubuntu-15-10-autostart/

**Comment by solvek** [comment]
Hello Anton
Thanks for the support.
I did what you've suggested but it still does not work.
After reboot web-ui does not work, however if I run 

> sudo /opt/traccar/bin/traccar start

 it works.

This is what I have in my syslog during the boot:

```
Sep 12 13:46:23 SolvekServer systemd[1]: Starting traccar...
...
Sep 12 13:46:23 SolvekServer traccar[2343]: Starting traccar...
Sep 12 13:46:27 SolvekServer traccar[2343]: Waiting for traccar......
Sep 12 13:46:27 SolvekServer traccar[2343]: running: PID:2416
Sep 12 13:46:27 SolvekServer systemd[1]: Started traccar.
Sep 12 13:46:31 SolvekServer systemd[1]: traccar.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 13:46:31 SolvekServer traccar[2842]: Stopping traccar...
Sep 12 13:46:31 SolvekServer traccar[2842]: traccar was not running.
Sep 12 13:46:31 SolvekServer systemd[1]: traccar.service: Unit entered failed state.
Sep 12 13:46:31 SolvekServer systemd[1]: traccar.service: Failed with result 'exit-code'.
```

**Comment by tananaev** [comment]
Check wrapper log file.

**Comment by solvek** [comment]
It looks like traccar cannot connect to mysql during the boot. Seems mysql is not started yet.

```
STATUS | wrapper  | 2016/09/12 13:46:23 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/12 13:46:23 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/12 13:46:23 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/12 13:46:23 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/12 13:46:23 | 
STATUS | wrapper  | 2016/09/12 13:46:24 | Launching a JVM...
INFO   | jvm 1    | 2016/09/12 13:46:24 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/12 13:46:24 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/09/12 13:46:24 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: liquibase.exception.DatabaseException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:157)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:65)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2165)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2090)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:239)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	... 12 more
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2106)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	... 23 more
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: Caused by: java.net.ConnectException: Connection refused
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at java.net.Socket.connect(Socket.java:589)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
INFO   | jvm 1    | 2016/09/12 13:46:29 | WrapperSimpleApp Error: 	... 25 more
STATUS | wrapper  | 2016/09/12 13:46:31 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Looks like that. Maybe you need to configure priority or dependencies.

**Comment by solvek** [comment]
Yes, finally managed to fix this.
I did the following

1. `sudo nano /etc/systemd/system/traccar.service`
2. Added `mysql.service` to `After` parameter (parameters are separated by space)

This is how my `traccar.service` looks like now:

```
[Unit]
Description=traccar
After=syslog.target mysql.service

[Service]
Type=forking
ExecStart=/opt/traccar/bin/traccar start sysd
ExecStop=/opt/traccar/bin/traccar stop sysd

[Install]
WantedBy=multi-user.target
```

**Comment by kirantpatil** [comment]
@tananaev, is Ubuntu 16.04 support (systemd) is pushed in v3.7 ?

**Comment by tananaev** [comment]
Version are not changed after release. The problem is with Java Service Wrapper and it exists in version 3.7 as far as I know. It's easy to fix by changing parameter in the wrapper script to enable systemd.
