### ISSUE TITLE
Error in Traccar 3.7 installation with mysql 5.7.9

### ISSUE THREAD

**Issue by bowo199** [tananaev/traccar#2342]
I try to install Traccar 3.7 with new mysql (5.7.9) database.

Is there something wrong with the nested sql query ? 
[Failed SQL: UPDATE dbtraccar.groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT id FROM groups) AS groups_ids)]

I found this error on wrapper log:

INFO   | jvm 1    | 2016/09/20 07:10:25 | INFO 9/20/16 7:10 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Foreign key constraint added to devices (groupid)
INFO   | jvm 1    | 2016/09/20 07:10:25 | SEVERE 9/20/16 7:10 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Change Set changelog-3.7::changelog-3.7::author failed.  Error: You can't specify target table 'groups' for update in FROM clause [Failed SQL: UPDATE dbtraccar.groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT id FROM groups) AS groups_ids)]
INFO   | jvm 1    | 2016/09/20 07:10:25 | INFO 9/20/16 7:10 AM: liquibase: changelog-3.7::changelog-3.7::author: Successfully released change log lock
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp:
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-3.7::changelog-3.7::author:
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: You can't specify target table 'groups' for update in FROM clause [Failed SQL: UPDATE dbtraccar.groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT id FROM groups) AS groups_ids)]
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:214)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:141)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:497)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error: Caused by: liquibase.exception.DatabaseException: You can't specify target table 'groups' for update in FROM clause [Failed SQL: UPDATE dbtraccar.groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT id FROM groups) AS groups_ids)]
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       at liquibase.changelog.ChangeSet.execute(ChangeSet.java:568)
INFO   | jvm 1    | 2016/09/20 07:10:25 | WrapperSimpleApp Error:       ... 15 more

**Comment by tananaev** [comment]
@Abyss777, remember this issue?

**Comment by Abyss777** [comment]
Yes, I remember. This construction was made specially for MySQL. It works perfect on:
````
mysql -V
mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (i686) using readline 6.3
````
and
````
mysql -V
mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
````
@bowo199 are you updating from 3.6 or creating new installation?

**Comment by bowo199** [comment]
i create new installation

**Comment by Abyss777** [comment]
@bowo199 You can comment/delete this 4 lines https://github.com/tananaev/traccar/blob/master/schema/changelog-3.7.xml#L18 in your installation.
It will allow pass this piece of changelog

If you don't mind, could you please run that sql request after successful installation via phpmyadmin or console?

**Comment by bowo199** [comment]
I've erased that line, but another error arises:

STATUS | wrapper  | 2016/09/20 13:42:14 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/20 13:42:14 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/20 13:42:14 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/20 13:42:14 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/20 13:42:14 |
STATUS | wrapper  | 2016/09/20 13:42:14 | Launching a JVM...
INFO   | jvm 1    | 2016/09/20 13:42:15 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/20 13:42:16 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/09/20 13:42:18 | INFO 9/20/16 1:42 PM: liquibase: Clearing database change log checksums
INFO   | jvm 1    | 2016/09/20 13:42:18 | INFO 9/20/16 1:42 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/09/20 13:42:18 | INFO 9/20/16 1:42 PM: liquibase: Creating database history table with name: mlacak_dbtrackPool32.DATABASECHANGELOG
INFO   | jvm 1    | 2016/09/20 13:42:18 | INFO 9/20/16 1:42 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/09/20 13:42:18 | INFO 9/20/16 1:42 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/09/20 13:42:21 | INFO 9/20/16 1:42 PM: liquibase: Reading from mlacak_dbtrackPool32.DATABASECHANGELOG
INFO   | jvm 1    | 2016/09/20 13:42:22 | INFO 9/20/16 1:42 PM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.3::changelog-3.3::author: Marking ChangeSet: changelog-3.3::changelog-3.3::author ran despite precondition failure due to onFail='MARK_RAN':
INFO   | jvm 1    | 2016/09/20 13:42:22 |           /opt/traccar/schema/changelog-master.xml : Not precondition failed
INFO   | jvm 1    | 2016/09/20 13:42:22 |
INFO   | jvm 1    | 2016/09/20 13:42:22 | INFO 9/20/16 1:42 PM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.5::changelog-3.5::author: Table groups created
INFO   | jvm 1    | 2016/09/20 13:42:22 | INFO 9/20/16 1:42 PM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.5::changelog-3.5::author: Table user_group created
INFO   | jvm 1    | 2016/09/20 13:42:22 | SEVERE 9/20/16 1:42 PM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.5::changelog-3.5::author: Change Set changelog-3.5::changelog-3.5::author failed.  Error: Cannot add foreign key constraint [Failed SQL: ALTER TABLE mlacak_dbtrackPool32.user_group ADD CONSTRAINT fk_user_group_userid FOREIGN KEY (userid) REFERENCES mlacak_dbtrackPool32.users (id) ON DELETE CASCADE]
INFO   | jvm 1    | 2016/09/20 13:42:22 | INFO 9/20/16 1:42 PM: liquibase: changelog-3.5::changelog-3.5::author: Successfully released change log lock
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp:
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-3.5::changelog-3.5::author:
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: Cannot add foreign key constraint [Failed SQL: ALTER TABLE mlacak_dbtrackPool32.user_group ADD CONSTRAINT fk_user_group_userid FOREIGN KEY (userid) REFERENCES mlacak_dbtrackPool32.users (id) ON DELETE CASCADE]
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:214)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:141)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/09/20 13:42:22 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by Abyss777** [comment]
Hm, first time you tried database with name `dbtraccar` but now it is `mlacak_dbtrackPool32`. Why? What are other differences in environment?

**Comment by bowo199** [comment]
I create new database again. 
I just want to know how to install traccar3.7 with clean database (new one).

After above error shown, i follow your tip to edit schema that trigger the error.
Above wrapper log show error on fk_user_group_userid block (changelog-3.5.xml)
so i try to edit it, but again, another wrapper error log arises.

Pls advice..

**Comment by Abyss777** [comment]
Is the environment still the same?
MySQL 5.7.9, new db is empty, with no tables?

**Comment by bowo199** [comment]
sorry, i have made mistake on dbname. Now it works.

But still, the manual sql command UPDATE dbtraccar.groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT id FROM groups) AS groups_ids)
keep returning this error:
Error in query (1093): You can't specify target table 'groups' for update in FROM clause

I think we need to modify the sql because we can't modify the same table which you use in the SELECT part. This behaviour is documented at: http://dev.mysql.com/doc/refman/5.6/en/update.html

**Comment by Abyss777** [comment]
I know that problem, because of that it has such weird construction. 
Actually `SELECT` happens from `groups_ids`, not from `groups`.
Frankly, I do not have more ideas why it happens. I'll try to rewrite it with `JOIN` for tests.
Is it possible to give me access to your phpmyadmin?

**Comment by bowo199** [comment]
Sure, i am using adminer.
I have sent the login info to your email abyss@fox5.ru

**Comment by Abyss777** [comment]
Here is improved request:
````
UPDATE groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM (SELECT DISTINCT id FROM groups) AS groups_ids);
````

`DISTINCT` forces to materialize derived table

There is also `optimizer_switch = 'derived_merge=off'` that should disable 5.7 behavior, but my is `derived_merge=on` as yours and it works.
http://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html#upgrade-sql-changes

@bowo199 thanks for possibility to debug the problem.

**Comment by tananaev** [comment]
Would `groupid NOT IN (SELECT DISTINCT id FROM groups)` work?

**Comment by bowo199** [comment]
@Abyss777 so DISTINCT is the key of the day.
How you can find it? You are great. works like a charm :)
no more wrapper error.

**Comment by Abyss777** [comment]
@tananaev unfortunately not.
Anyway, we can use 100% working solution:
````
CREATE TEMPORARY TABLE groups_ids (id INT) SELECT id FROM groups;
UPDATE groups SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM groups_ids);
DROP TABLE groups_ids;
````

**Comment by tananaev** [comment]
If it works for all database engines, can you please send me a pull request.

**Comment by Abyss777** [comment]
Sure, after tests on H2, pg and ms I will make a pull request.

Just curious, how much time took original request on demo server? It should be logged in wrapper.log.

**Comment by tananaev** [comment]
It was a long time ago and I cleared logs, so I don't have it.

**Comment by Abyss777** [comment]
I hurried, this 3 line request do not work on ms and pg.
`DISTINCT` work on all (H2, mysql, pgsql, mssql)
