### ISSUE TITLE
OpenGTS working on version 3.4 but not working with latest 3.7

### ISSUE THREAD

**Issue by himsashu** [tananaev/traccar#2523]
Hi Tananaev
I was using Traccar 3.4 version with OpenGTS. Yesterday I updated it to 3.7 and now it is not working.

```
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!-- SERVER CONFIG -->

    <entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <!-- DATABASE CONFIG -->

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/gts?allowMultiQueries=true</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>lalmani123</entry>

    <entry key='database.selectDevicesAll'>
		SELECT imeiNumber AS id, imeiNumber AS uniqueID FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
    </entry>
    <entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:fixTime), lastUpdateTime = UNIX_TIME$
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :address);
			COMMIT;
    </entry>
	
    <entry key='gt06.port'>5023</entry>
</properties>
```

The wrapper.log file looks link below:
```
STATUS | wrapper  | 2016/11/10 09:54:57 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/11/10 09:54:57 | Java Service Wrapper Community Edition 32-bit 3.5.28
STATUS | wrapper  | 2016/11/10 09:54:57 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/11/10 09:54:57 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/11/10 09:54:57 | 
STATUS | wrapper  | 2016/11/10 09:54:57 | Launching a JVM...
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/11/10 09:54:58 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/11/10 09:54:58 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.Connection.getNetworkTimeout()I)
INFO   | jvm 1    | 2016/11/10 09:54:58 | [WrapperSimpleAppMain] ERROR com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (com.mysql.jdbc.Connection.isValid(I)Z)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: com.mysql.jdbc.Connection.isValid(I)Z
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabase(DataManager.java:111)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:66)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: Caused by: java.lang.AbstractMethodError: com.mysql.jdbc.Connection.isValid(I)Z
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:400)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:375)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:508)
INFO   | jvm 1    | 2016/11/10 09:54:58 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2016/11/10 09:55:01 | <-- Wrapper Stopped
```

I don't know what is wrong with this. Please help me.
The same configuration is working file on Traccar version 3.4

**Comment by tananaev** [comment]
Are you sure you've updated everything correctly? It seems like you have some problem with database driver.

**Comment by himsashu** [comment]
I have only updated the Traccar Version, nothing else. Guide me what I need to do now.

**Comment by tananaev** [comment]
What do you mean by that? Please describe step by step what you did.

**Comment by himsashu** [comment]
I really sorry for my reply.
Your hint was right. After updating database driver everything is ok.
Thanks for your support.
