### ISSUE TITLE
ning http client exception Executing traccar.jar build from intellij idea 

### ISSUE THREAD

**Issue by AmmarBashir** [tananaev/traccar#2533]
Hello
I have build jar file with intellij idea with traccar. 
and downloaded files for manual installation files from https://www.traccar.org/manual-installation/
then i replace my jar file with tracker-server.jar and installed it with this command in windows cli

java -jar traccar.jar conf/traccar.xml 

where
 traccar.jar is my build from intellij
In traccar.xml I have file paths and database connection string to my local db

I have windows 10 x64 and jdk 1.8 

I am getting this error
Exception in thread "main" java.lang.NoClassDefFoundError: com/ning/http/client/AsyncHttpClient
        at org.traccar.Context.<clinit>(Context.java:130)
        at org.traccar.Main.main(Main.java:35)
Caused by: java.lang.ClassNotFoundException: com.ning.http.client.AsyncHttpClient
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

but when installing original tracker-server.jar file it install with no problem

Any help would be appreciated

**Comment by tananaev** [comment]
The error means that a library is missing. I guess either file is missing, or your JAR file doesn't have correct class path. I would recommend to build using maven directly, not from IDEA.

**Comment by Kanakala** [comment]
@AmmarBashir, I got the same issue as you described. Have you resolved the problem. If so, Can you please explain me!!
I would appreciate helping me solve this.

**Comment by hmglobal** [comment]
@Kanakala, estimated, how to solve that problem is very easy, when compiling the application with maven two jar files are generated, the first one named tracker-server.jar and the second named tracker-server-jar-with- Dependencies.jar. What you should do Is to display the second file called tracker-server-jar-with-dependencies.jar. that is all.

regards..

Pd: sorry for my english.
