### ISSUE TITLE
failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by skylabz0rz** [tananaev/traccar#2709]
Hello,

I am attempting to upgrade from 3.5 to 3.9 on a CENTOS 6.8 server. Using Java SE 1.8.0_101-b13.

Backed up the config file, deleted the directory and reuploaded the file.

When I ran the command "bash traccar.run" It started to extract as expected. However, it stopped here:
```
---------- YAJSW SET ENV ----------
YAJSW: yajsw-beta-12.07
OS   : Linux/2.6.32-642.6.2.el6.x86_64/amd64
JVM  : Oracle Corporation/1.8.0_101//opt/jdk1.8.0_101/jre/64
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna4079193711957452714.tmp: /tmp/jna-3506402/jna4079193711957452714.tmp: failed to map segment from shared object: Operation not permitted
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
        at com.sun.jna.Native.<clinit>(Native.java:131)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.PointerType.<init>(PointerType.java:25)
        at com.sun.jna.ptr.ByReference.<init>(ByReference.java:30)
        at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:22)
        at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:18)
        at org.rzo.yajsw.os.posix.PosixProcess.<init>(PosixProcess.java:67)
        at org.rzo.yajsw.os.posix.OperatingSystemPosix.setWorkingDir(OperatingSystemPosix.java:27)
        at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:115)
        ... 5 more
```

Any thoughts?

**Comment by tananaev** [comment]
Looks like there are some problems with `/tmp` folder.

**Comment by skylabz0rz** [comment]
Ended up having to add exec to the tmp drive via sudo mount /tmp -o remount,exec. Script ran after that.

**Comment by skylabz0rz** [comment]
After changing the tmp file as above, I was able to start the server but it refuses any connections. Error log for the wrapper states:

INFO|26314/0|Service traccar|16-12-19 14:40:55|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|26314/0|Service traccar|16-12-19 14:40:56|java.lang.reflect.InvocationTargetException
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|26314/0|Service traccar|16-12-19 14:40:56|Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 105; The reference to entity "autoReconnect" must end with the ';' delimiter.
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at java.util.Properties$XmlSupport.load(Properties.java:1201)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at java.util.Properties.loadFromXML(Properties.java:881)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at org.traccar.Config.load(Config.java:30)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at org.traccar.Context.init(Context.java:168)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	at org.traccar.Main.main(Main.java:35)
INFO|26314/0|Service traccar|16-12-19 14:40:56|	... 6 more

Is this still with the tmp directory having something wrong with it?

**Comment by tananaev** [comment]
Now you have invalid XML in your config file:
> lineNumber: 25; columnNumber: 105; The reference to entity "autoReconnect" must end with the ';' delimiter.

**Comment by skylabz0rz** [comment]
Ah yes. I can't believe I missed that. 

Once updated, I got past that step but now I get this upon connecting to the database: 

INFO|5005/0|Service traccar|16-12-19 14:54:55|INFO 12/19/16 2:54 PM: liquibase: Reading from ridesmar_gps2.DATABASECHANGELOG
INFO|5005/0|Service traccar|16-12-19 14:54:55|INFO 12/19/16 2:54 PM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Can't DROP 'uk_user_token'; check that column/key exists [Failed SQL: ALTER TABLE ridesmar_gps2.users DROP KEY uk_user_token]
INFO|5005/0|Service traccar|16-12-19 14:54:55|INFO 12/19/16 2:54 PM: liquibase: Successfully released change log lock

**Comment by tananaev** [comment]
That's not an issue, you can safely ignore the message.

**Comment by skylabz0rz** [comment]
Got it. Thanks. Everything looks to be on the up and up.
