### ISSUE TITLE
Cant execute traccar.run on Centos 6.8

### ISSUE THREAD

**Issue by jatindhoot** [tananaev/traccar#2727]
Hello,

My Linux version is:-

> lsb_release -irc
> Distributor ID:	CentOS
> Release:	6.8
> Codename:	Final

When I am trying to install traccar **3.9** via **sh traccar.run** I am getting following heap of errors:-

```
---------- YAJSW SET ENV ----------
YAJSW: yajsw-beta-12.07
OS   : Linux/2.6.32-642.6.2.el6.x86_64/amd64
JVM  : Oracle Corporation/1.7.0_121//usr/lib/jvm/java-1.7.0-openjdk-1.7.0.121.x86_64/jre/64
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna1645823449535801527.tmp: /tmp/jna-3506402/jna1645823449535801527.tmp: failed to map segment from shared object: Operation not permitted
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
	at com.sun.jna.Native.<clinit>(Native.java:131)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.PointerType.<init>(PointerType.java:25)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:30)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:22)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:18)
	at org.rzo.yajsw.os.posix.PosixProcess.<init>(PosixProcess.java:67)
	at org.rzo.yajsw.os.posix.OperatingSystemPosix.setWorkingDir(OperatingSystemPosix.java:27)
	at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:115)
	... 5 more

```

Out put of `java -version` is as under:-

```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

```

Kind regards

**Comment by tananaev** [comment]
Looks like you have some issue with `/tmp` folder.

**Comment by jatindhoot** [comment]
Hello,

Thanks for your reply.

I moved in home directory and tried to execute, but problem still persists.

Kind regards

**Comment by tananaev** [comment]
How is home directory related to the problem with tmp directory?

**Comment by jatindhoot** [comment]
I am sorry.

I thought you want to say that instead of executing from /tmp execute it from elsewhere.

Please suggest workaround.

Regards

**Comment by tananaev** [comment]
Check #2709.

**Comment by jatindhoot** [comment]
Thanks heaps ,it worked like magic.

**Comment by tananaev** [comment]
Looks like it's a bug in YAJSW. Create a ticket in their bug tracker:

https://sourceforge.net/p/yajsw/bugs/130/

**Comment by tananaev** [comment]
Sorry, it was mostly a note for myself :)

**Comment by jatindhoot** [comment]
No problems mate, you guys are really working hard. Keep the good work up and running :-)
