### ISSUE TITLE
Traccar server starts but server wont load after changing config to use MySQL instead of H2 database

### ISSUE THREAD

**Issue by jatindhoot** [tananaev/traccar#2731]
Hello,

After installing traccar, I changed traccar.xml to use MySQL server instead of default H2 database. Changes were as under:-

```
<entry key='database.url'>jdbc:mysql://SERVER:3306/DB?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>USER</entry> 
<entry key='database.password'>PASS</entry>

```

When I start traccar via sh startDaemon.sh, I get success messages as under:-

```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
---------- YAJSW SET ENV ----------
YAJSW: yajsw-beta-12.07
OS   : Linux/2.6.32-642.6.2.el6.x86_64/amd64
JVM  : Oracle Corporation/1.8.0_111//usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre/64
Dec 26, 2016 11:23:27 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "/tmp/vfs_cache" as temporary files store.
Dec 26, 2016 11:23:27 PM org.rzo.yajsw.os.posix.PosixService init
INFO: /etc/init.d/traccar already exists
************* STARTING traccar ***********************

Dec 26, 2016 11:23:27 PM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /var/run/wrapper.traccar.pid
Dec 26, 2016 11:23:30 PM org.rzo.yajsw.os.posix.PosixService start
INFO: Starting traccar ...
YAJSW: yajsw-beta-12.07
OS   : Linux/2.6.32-642.6.2.el6.x86_64/amd64
JVM  : Oracle Corporation/1.8.0_111//usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64/jre/64
************* STARTING traccar ***********************

Service traccar started

Dec 26, 2016 11:23:30 PM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /var/run/wrapper.traccar.pid
Dec 26, 2016 11:23:31 PM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /var/run/wrapper.traccar.pid
Dec 26, 2016 11:23:31 PM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /var/run/wrapper.traccar.pid
Service traccar started

```

But when I tried to execute server in web browser, page wont load.

I can see entries in error log as under:-

```
INFO|wrapper|Service traccar|16-12-26 23:15:54|posix_spawn pid 19897
INFO|wrapper|Service traccar|16-12-26 23:15:54|started process 19897
INFO|wrapper|Service traccar|16-12-26 23:15:54|started process with pid 19897
INFO|19897/0|Service traccar|16-12-26 23:15:55|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|19897/0|Service traccar|16-12-26 23:15:55|java.lang.reflect.InvocationTargetException
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|19897/0|Service traccar|16-12-26 23:15:55|Caused by: java.lang.RuntimeException: Failed to load class of driverClassName null
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:323)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.traccar.database.DataManager.initDatabase(DataManager.java:99)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.traccar.Context.init(Context.java:176)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at org.traccar.Main.main(Main.java:35)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	... 6 more
INFO|19897/0|Service traccar|16-12-26 23:15:55|Caused by: java.lang.NullPointerException
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:307)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:318)
INFO|19897/0|Service traccar|16-12-26 23:15:55|	... 10 more
INFO|wrapper|Service traccar|16-12-26 23:15:56|waitpid 19897 59136
INFO|wrapper|Service traccar|16-12-26 23:15:56|exit code posix process: 59136 application: 0

```

Kindly help.

Regards

**Comment by Abyss777** [comment]
Looks like you have forgotten point the driver
https://www.traccar.org/mysql/

**Comment by jatindhoot** [comment]
Exactly it was the problem.

Thanks
