### ISSUE TITLE
Can't run with netbeans

### ISSUE THREAD

**Issue by mgmskumara** [tananaev/traccar#2733]
Hi,
First i want to say, I'm new to traccar and have not work with maven projects.

I tried to build source codeof traccar(Server)  with netbeans IDE. But when i try to run it gives me these errors. If you have any experience please help me.

cd E:\trackcar\traccar; "JAVA_HOME=C:\\Program Files (x86)\\Java\\jdk1.8.0_111" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath org.traccar.Main debug.xml\" -Dexec.executable=\"C:\\Program Files (x86)\\Java\\jdk1.8.0_111\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building traccar 3.8-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x7472c3e1, pid=3608, tid=0x00000c1c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) Client VM (25.111-b14 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [chtbrkg.dll+0x1c3e1]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\trackcar\traccar\hs_err_pid3608.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.417s
Finished at: Tue Dec 27 21:03:50 IST 2016
Final Memory: 7M/18M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project traccar: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Thank you,
Kumara

**Comment by tananaev** [comment]
Looks like there is some problem with Java Virtual Machine.

**Comment by mgmskumara** [comment]
Hi,
Thank you for your reply.
Actually i had a problem with a dll. I have to remove CHTBRKG.DLL.

Now i have a problem like this.
If you have any experience please try to help me.

--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
[main] ERROR com.ning.http.client.AsyncHttpClient - Unable to instantiate provider com.ning.http.client.providers.netty.NettyAsyncHttpProvider.  Trying other providers.
[main] ERROR com.ning.http.client.AsyncHttpClient - org.jboss.netty.channel.ChannelException: Failed to create a selector.
org.jboss.netty.channel.ChannelException: Failed to create a selector.
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:362)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52)
	at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151)
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:133)
	at com.ning.http.client.providers.netty.channel.ChannelManager.<init>(ChannelManager.java:188)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.<init>(NettyAsyncHttpProvider.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.ning.http.client.AsyncHttpClient.loadDefaultProvider(AsyncHttpClient.java:565)
	at com.ning.http.client.AsyncHttpClient.<init>(AsyncHttpClient.java:187)
	at com.ning.http.client.AsyncHttpClient.<init>(AsyncHttpClient.java:167)
	at org.traccar.Context.<clinit>(Context.java:128)
	at org.traccar.Main.main(Main.java:35)
Caused by: java.io.IOException: Unable to establish loopback connection

Thank you,
Kumara

**Comment by tananaev** [comment]
It doesn't sound right that you just remove a DLL. It seems like there are some serious problem either with your Windows or Java.
