### ISSUE TITLE
blind forward of parsed packets

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#2738]
Hello,
I've installed traccar v3.9 under linux and I'm trying to forward all parsed data packets from GT06N trackers to another web server.
I want traccar to blindly forward any GT06N packet to the other web server.  Which fails.
Here's the traccar.xml I'm using:

```
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!-- SERVER CONFIG -->

    <entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>
    <entry key='web.type'>old</entry>
    <entry key='web.application'>/opt/traccar/traccar-web.war</entry>   

    <entry key='geocoder.enable'>false</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <entry key='forward.enable'>true</entry>
	<entry key='forward.url'>http://45.221.12.24:8765/gprmc/Data?id={uniqueId}&amp;code=0x0000&amp;gprmc={gprmc}</entry>

	<!-- PROTOCOL CONFIG -->
    <entry key='gt06.port'>40066</entry>
</properties>

```

with this config traccar didn't even start and I get in log:
```

WARNING|wrapper|Service traccar|16-12-28 17:38:30|YAJSW: yajsw-beta-12.07
WARNING|wrapper|Service traccar|16-12-28 17:38:30|OS   : Linux/4.4.0-57-generic/amd64
WARNING|wrapper|Service traccar|16-12-28 17:38:30|JVM  : Oracle Corporation/1.7.0_95//usr/lib/jvm/java-7-openjdk-amd64/jre/64
INFO|wrapper|Service traccar|16-12-28 17:38:31|exec:"java" "-classpath" "/opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j-1.2.17.jar:/opt/traccar/lib/joda-time-2.9.6.jar:/opt/traccar/lib/h2-1.4.193.jar:/opt/traccar/lib/mysql-connector-java-5.1.40.jar:/opt/traccar/lib/postgresql-9.4.1212.jre7.jar:/opt/traccar/lib/mssql-jdbc-6.1.0.jre7.jar:/opt/traccar/lib/HikariCP-java7-2.4.9.jar:/opt/traccar/lib/slf4j-api-1.7.21.jar:/opt/traccar/lib/netty-3.10.6.Final.jar:/opt/traccar/lib/async-http-client-1.9.40.jar:/opt/traccar/lib/slf4j-simple-1.7.21.jar:/opt/traccar/lib/javax.json-1.0.4.jar:/opt/traccar/lib/jetty-server-9.2.19.v20160908.jar:/opt/traccar/lib/javax.servlet-api-3.1.0.jar:/opt/traccar/lib/jetty-http-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-io-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-security-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-webapp-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-xml-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-jndi-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-util-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-server-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-common-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-api-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-client-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jersey-container-servlet-2.24.jar:/opt/traccar/lib/jersey-container-servlet-core-2.24.jar:/opt/traccar/lib/javax.inject-2.5.0-b05.jar:/opt/traccar/lib/jersey-common-2.24.jar:/opt/traccar/lib/javax.annotation-api-1.2.jar:/opt/traccar/lib/jersey-guava-2.24.jar:/opt/traccar/lib/hk2-api-2.5.0-b05.jar:/opt/traccar/lib/hk2-utils-2.5.0-b05.jar:/opt/traccar/lib/aopalliance-repackaged-2.5.0-b05.jar:/opt/traccar/lib/hk2-locator-2.5.0-b05.jar:/opt/traccar/lib/javassist-3.20.0-GA.jar:/opt/traccar/lib/osgi-resource-locator-1.0.1.jar:/opt/traccar/lib/jersey-server-2.24.jar:/opt/traccar/lib/jersey-client-2.24.jar:/opt/traccar/lib/jersey-media-jaxb-2.24.jar:/opt/traccar/lib/validation-api-1.1.0.Final.jar:/opt/traccar/lib/javax.ws.rs-api-2.0.1.jar:/opt/traccar/lib/jersey-media-json-jackson-2.24.jar:/opt/traccar/lib/jersey-entity-filtering-2.24.jar:/opt/traccar/lib/jackson-jaxrs-base-2.5.4.jar:/opt/traccar/lib/jackson-core-2.5.4.jar:/opt/traccar/lib/jackson-databind-2.5.4.jar:/opt/traccar/lib/jackson-jaxrs-json-provider-2.5.4.jar:/opt/traccar/lib/jackson-module-jaxb-annotations-2.5.4.jar:/opt/traccar/lib/jackson-annotations-2.5.4.jar:/opt/traccar/lib/liquibase-core-3.5.3.jar:/opt/traccar/lib/snakeyaml-1.17.jar:/opt/traccar/lib/mail-1.4.7.jar:/opt/traccar/lib/activation-1.1.jar:/opt/traccar/lib/jxls-2.3.0.jar:/opt/traccar/lib/commons-jexl-2.1.1.jar:/opt/traccar/lib/commons-logging-1.1.1.jar:/opt/traccar/lib/commons-beanutils-1.9.2.jar:/opt/traccar/lib/jcl-over-slf4j-1.7.12.jar:/opt/traccar/lib/logback-core-1.1.3.jar:/opt/traccar/lib/jxls-poi-1.0.11.jar:/opt/traccar/lib/poi-3.14.jar:/opt/traccar/lib/commons-codec-1.10.jar:/opt/traccar/lib/poi-ooxml-3.14.jar:/opt/traccar/lib/poi-ooxml-schemas-3.14.jar:/opt/traccar/lib/xmlbeans-2.6.0.jar:/opt/traccar/lib/stax-api-1.0.1.jar:/opt/traccar/lib/curvesapi-1.03.jar:/opt/traccar/lib/velocity-1.7.jar:/opt/traccar/lib/commons-collections-3.2.1.jar:/opt/traccar/lib/commons-lang-2.4.jar" "-Dfile.encoding=UTF-8" "-Xrs" "-Dwrapper.service=true" "-Dwrapper.console.visible=false" "-Dwrapper.port=15003" "-Dwrapper.key=-2655006776320711304" "-Dwrapper.teeName=-2655006776320711304$1482943110846" "-Dwrapper.tmp.path=/opt/traccar/tmp" "-Djna_tmpdir=/opt/traccar/tmp" "-Dwrapper.config=/opt/traccar/conf/wrapper.conf" "-Dwrapper.visible=false" "-Dwrapper.pidfile=/run/wrapper.traccar.pid" "org.rzo.yajsw.app.WrapperJVMMain" 
INFO|wrapper|Service traccar|16-12-28 17:38:31|posix_spawn pid 5924
INFO|wrapper|Service traccar|16-12-28 17:38:31|started process 5924
INFO|wrapper|Service traccar|16-12-28 17:38:31|started process with pid 5924
INFO|5924/0|Service traccar|16-12-28 17:38:32|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|5924/0|Service traccar|16-12-28 17:38:33|java.lang.reflect.InvocationTargetException
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at java.lang.reflect.Method.invoke(Method.java:606)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|5924/0|Service traccar|16-12-28 17:38:33|Caused by: java.lang.NullPointerException
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.traccar.database.PermissionsManager.refreshUsers(PermissionsManager.java:88)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:80)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.traccar.Context.init(Context.java:244)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	at org.traccar.Main.main(Main.java:35)
INFO|5924/0|Service traccar|16-12-28 17:38:33|	... 6 more
INFO|wrapper|Service traccar|16-12-28 17:38:34|waitpid 5924 59136
INFO|wrapper|Service traccar|16-12-28 17:38:34|exit code posix process: 59136 application: 0

```

If I reset db keys in config file, traccar server starts, but warn about unknow device and gps data don't get forwarded. Can I have packets forwarded without adding devices to database?

Regards,

**Comment by tananaev** [comment]
You can use Traccar without a database, but you can configure to automatically register unknown devices using `database.registerUnknown` parameter in the config.

**Comment by slachtar** [comment]
Thank you for your reply,
Nice to hear there is a database.registerUnknown param. Very useful.
But could you please tell me how to use traccar without db. Because when I remove db keys like shown in the initial config file, the server doesn't start.
Thank you again.

**Comment by tananaev** [comment]
Sorry, there was a typo. You CAN'T use it without database. But you can use default database and only save list of devices there, nothing else.

**Comment by slachtar** [comment]
No problem.
Yes I was thinking about that too. so I can use the default db just to
register unknown devices and this way I'll have forwarding work.
Thank you again.

**Comment by tananaev** [comment]
Yes, that's the way I set it up for some clients that needed only forwarding functionality.

**Comment by slachtar** [comment]
I'll close issue. Thank you again.
