### ISSUE TITLE
traccar config SQL server.

### ISSUE THREAD

**Issue by SRIKAAA** [tananaev/traccar#2758]
INFO   | jvm 1    | 2017/01/05 16:29:09 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/01/05 16:29:10 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2017/01/05 16:29:10 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp: 
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:160)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: Caused by: java.lang.RuntimeException: Cannot find database driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:199)
INFO   | jvm 1    | 2017/01/05 16:29:11 | WrapperSimpleApp Error: 	... 12 more
STATUS | wrapper  | 2017/01/05 16:29:14 | <-- Wrapper Stopped

what could be the error?

**Comment by tananaev** [comment]
As you can see from the log, the error is that the database driver is missing.

What version of Traccar are you using? Latest release (3.9) includes MS SQL driver.
