### ISSUE TITLE
Invalid char in device name

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2955]
Looks like some characters cause issue with Excel reports:
```
FINEST|10708/0|Service traccar|17-02-25 22:19:17|[qtp374646930-40] ERROR org.jxls.area.XlsArea - Failed to transform template!H9 into 'Dacia Dokker[GD239HP]'!H11
FINEST|10708/0|Service traccar|17-02-25 22:19:17|java.lang.IllegalArgumentException: Invalid char ([) found at index (12) in sheet name 'Dacia Dokker[GD239HP]'
FINEST|10708/0|Service traccar|17-02-25 22:19:17|	at org.apache.poi.ss.util.WorkbookUtil.validateSheetName(WorkbookUtil.java:154)
FINEST|10708/0|Service traccar|17-02-25 22:19:17|	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:794)
FINEST|10708/0|Service traccar|17-02-25 22:19:17|	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:109)
FINEST|10708/0|Service traccar|17-02-25 22:19:17|	at org.jxls.transform.poi.PoiTransformer.transform(PoiTransformer.java:116)
FINEST|10708/0|Service traccar|17-02-25 22:19:17|	at org.jxls.area.XlsArea.transformStaticCells(XlsArea.java:460)
...
```

I guess group name might have similar issue as well.

@Abyss777, can you please take a look.

**Comment by Abyss777** [comment]
Yes, there is some limitations  in worksheet names (square brackets and others)
http://stackoverflow.com/questions/451452/valid-characters-for-excel-sheet-names

I'll try to use http://poi.apache.org/apidocs/org/apache/poi/ss/util/WorkbookUtil.html#createSafeSheetName(java.lang.String)
