### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by akmal1999** [tananaev/traccar#3356]
Hi 
Did did anyone get this database issue? Does anyone resolved and how?

2017-07-16 14:59:54  WARN: Table 'databas.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:318 < PermissionsManager:85 < ...)
2017-07-16 14:59:54  WARN: Table 'database.user_group' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:197 < PermissionsManager:100 < ...)

Appreciated your help.

**Comment by santushet** [comment]
I did not get this issue. But from the log it looks like tables "server","
user_group " are not available. They might have been deleted after
installation or not created during installation. You can consider
uninstalling and installing again.

On Jul 16, 2017 10:38 PM, "akmal1999" <notifications@github.com> wrote:

Hi
Did did anyone get this database issue? Does anyone resolved and how?

2017-07-16 14:59:54 WARN: Table 'databas.server' doesn't exist -
MySQLSyntaxErrorException (... < QueryBuilder:388 < *:284 < DataManager:318
< PermissionsManager:85 < ...)
2017-07-16 14:59:54 WARN: Table 'database.user_group' doesn't exist -
MySQLSyntaxErrorException (... < QueryBuilder:388 < DataManager:197 <
PermissionsManager:100 < ...)

Appreciated your help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3356>, or mute the thread

**Comment by akmal1999** [comment]
[tracker-serveramended.log.txt](https://github.com/tananaev/traccar/files/1151189/tracker-serveramended.log.txt)


[wrapper.log.zip](https://github.com/tananaev/traccar/files/1151203/wrapper.log.zip)

**Comment by akmal1999** [comment]
here are the logs

**Comment by akmal1999** [comment]
Well instead of un installing and installing is there a workaround available? for instance exporting and importing this table from another database?

**Comment by akmal1999** [comment]
@santushet

**Comment by tananaev** [comment]
There is something wrong with your database. If you don't want to re-create it, you would have to manually fix it.

**Comment by akmal1999** [comment]
I will recreate or add those tables...

I have issue with the devices not coming online while they are on.. and we are missing one day of data while alot of people worked.... that is why i uploaded the logs.

**Comment by tananaev** [comment]
Well, you would have to select some relevant information from the logs or pay for premium support. I'm not going to look through 4MB of logs files otherwise.

**Comment by akmal1999** [comment]
hi,

Following error in tracker-server.log

7/16/2017	17:28:09	INFO:	[51EA102C]	id:		7/15/2017	"18:05:40,"	lat:	"46.64254,"	lon:	"27.47406,"	speed:	"0.0,"	course:	0			
7/16/2017	17:28:09	WARN:	[B6106B8F]	error		reset	by	peer	-	IOException	(...)							
7/16/2017	17:28:09	INFO:	[B6106B8F]	disconnected														
7/16/2017	17:28:09	INFO:	[2E9FF74B]	id:		7/16/2017	"11:56:50,"	lat:	"53.75014,"	lon:	"-2.01346,"	speed:	"0.5,"	course:	204.5			
7/16/2017	17:28:09	DEBUG:	[B66B2BB8:	5055		HEX:	474554202f3f69643d3738323139312674696d657374616d703d31353030313438383337266c61743d35332e3832373132353130373733373337266c6f6e3d2d312e353035363732383534343132353134362673706565643d302e302662656172696e673d302e3026616c7469747564653d3133312e323333303331323130343035333626626174743d34372e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420372e303b20534d2d4739323546204275696c642f4e524439304d290d0a486f73743a203136322e3134342e3130332e3233373a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a											
7/16/2017	17:28:09	DEBUG:	[B66B2BB8:	5055		HEX:	485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a											
7/16/2017	17:28:09	INFO:	[CD85BC55]	id:		7/16/2017	"11:21:37,"	lat:	"53.97121,"	lon:	"-1.04512,"	speed:	"3.1,"	course:	304			
7/16/2017	17:28:09	INFO:	[CD85BC55]	disconnected														
7/16/2017	17:28:09	INFO:	[B66B2BB8]	disconnected														
7/16/2017	17:28:09	INFO:	[D090D849]	id:		7/16/2017	"11:05:46,"	lat:	"53.77650,"	lon:	"-1.54071,"	speed:	"4.8,"	course:	35.6			
7/16/2017	17:28:09	INFO:	[D090D849]	disconnected														
7/16/2017	17:28:09	DEBUG:	[E8B8FF9C:	5055		HEX:	474554202f3f69643d3335353336372674696d657374616d703d31353030323236303732266c61743d35332e37393030323637266c6f6e3d2d312e353531333239332673706565643d302e302662656172696e673d302e3026616c7469747564653d37392e383030303033303531373537383126626174743d31362e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342e342e323b2050365f516d6178204275696c642f4b4f54343948290d0a486f73743a203136322e3134342e3130332e3233373a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a											
7/16/2017	17:28:09	DEBUG:	[E8B8FF9C:	5055		HEX:	485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a											
7/16/2017	17:28:09	INFO:	[E8B8FF9C]	disconnected														
7/16/2017	17:28:09	INFO:	[C0BA7D77]	disconnected														
7/16/2017	17:28:10	INFO:	[2E9FF74B]	id:		7/16/2017	"11:56:05,"	lat:	"53.75049,"	lon:	"-2.01281,"	speed:	"3.4,"	course:	204.5			
7/16/2017	17:28:10	INFO:	[25DB44B8]	id:		7/16/2017	"11:30:51,"	lat:	"53.84560,"	lon:	"-1.76124,"	speed:	"0.0,"	course:	104.8			
7/16/2017	17:28:10	INFO:	[9F333098]	id:		7/16/2017	"12:08:15,"	lat:	"53.78081,"	lon:	"-1.56412,"	speed:	"2.2,"	course:	196.3			
7/16/2017	17:28:10	INFO:	[F7DC25B0]	id:		7/16/2017	"10:21:03,"	lat:	"53.72426,"	lon:	"-1.71663,"	speed:	"0.0,"	course:	0			
7/16/2017	17:28:10	INFO:	[C908ED09]	id:		7/16/2017	"10:32:08,"	lat:	"53.98034,"	lon:	"-1.14728,"	speed:	"2.7,"	course:	79.1			
7/16/2017	17:28:10	INFO:	[D950690B]	id:		7/16/2017	"12:58:06,"	lat:	"53.91614,"	lon:	"-1.14424,"	speed:	"1.0,"	course:	134.7			
7/16/2017	17:28:10	INFO:	[CD85BC55]	id:		7/16/2017	"11:19:22,"	lat:	"53.97171,"	lon:	"-1.04426,"	speed:	"2.6,"	course:	290.9			
7/16/2017	17:28:10	INFO:	[1EC9ED67]	id:		7/16/2017	"11:32:04,"	lat:	"53.37714,"	lon:	"-1.53011,"	speed:	"20.4,"	course:	79.5			
7/16/2017	17:28:10	INFO:	[567E9A0B]	id:		7/16/2017	"11:20:40,"	lat:	"53.74449,"	lon:	"-1.75990,"	speed:	"1.2,"	course:	235.3			
7/16/2017	17:28:10	INFO:	[CD85BC55]	id:		7/16/2017	"10:41:22,"	lat:	"53.97212,"	lon:	"-1.04191,"	speed:	"3.0,"	course:	140.4			
7/16/2017	17:28:10	INFO:	[CEB059B7]	id:		7/16/2017	"10:44:28,"	lat:	"53.77604,"	lon:	"-1.55159,"	speed:	"0.0,"	course:	0

**Comment by akmal1999** [comment]
Hi, 
Here is the wrapper log error:

[WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2017/07/16 17:27:46 | Exception in thread "pool-4-thread-1" java.lang.InternalError: java.io.FileNotFoundException: /usr/java/jdk1.8.0_131/jre/lib/ext/localedata.jar (Too many open files)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1040)

------------------

org.jboss.netty.logging.JdkLogger.warn(JdkLogger.java:80)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:340)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2017/07/16 17:27:46 | Caused by: java.io.FileNotFoundException: /usr/java/jdk1.8.0_131/jre/lib/ext/localedata.jar (Too many open files)
INFO   | jvm 1    | 2017/07/16 17:27:46 | 	at java.util.zip.ZipFile.open(Native Method)

**Comment by tananaev** [comment]
Wrapper log indicates that you reached the limit on number of open file descriptors (connections). This problem has been discussed here and on forum many times.
