### ISSUE TITLE
Traccar Service stops early after initializing

### ISSUE THREAD

**Issue by stevenseh** [tananaev/traccar#3362]
Hi there!
The traccar service stops early during initialization.
Seems there is a binding issue.
I think I has this problem befor, but I cannot find my old issues..
Below is the log.
What bindings are causing trouble?
How do I un-bind?
Thanks,
Eric

INFO|3816/0|Service traccar|17-07-17 16:13:54|Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5001
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.traccar.TrackerServer.start(TrackerServer.java:117)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.traccar.ServerManager.start(ServerManager.java:81)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.traccar.Main.main(Main.java:38)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	... 6 more
INFO|3816/0|Service traccar|17-07-17 16:13:54|Caused by: java.net.BindException: Address already in use: bind
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at sun.nio.ch.Net.bind0(Native Method)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO|3816/0|Service traccar|17-07-17 16:13:54|	at java.lang.Thread.run(Unknown Source)
INFO|wrapper|Service traccar|17-07-17 16:13:54|calling onStop

**Comment by tananaev** [comment]
Have you tried searching first? This issue has been discussed many times. You have a port conflict with some other process on you machine.

**Comment by stevenseh** [comment]
I wouldn't have started this issue if I had found the answer. There are many posts, true, but of the 15 I read, help resolve the issue I have now. Please give me some pointer.
svchost.exe is the process that uses port 5001, which I suppose is the one causing the issue. Correct me if I'm wrong.
Can I change the port from 5001 to something else in config. If the answer is yes, please thell me what entry of the config file I should use.
Thanks
Eric

**Comment by tananaev** [comment]
How can I confirm something that I don't know? It can be any process on your system.

You can change or remove port in the config file:

https://www.traccar.org/configuration-file/

**Comment by stevenseh** [comment]
Because I knew that you would point me to the config file, I explicitly asked you for the entry in which to change the conflict with port 5001 - I still assume that that's the one that is causing the issue, as you didn't point out that y assumption was incorrect. Please be specific.
Thanks,
Eric

**Comment by stevenseh** [comment]
I tried changing the ports of the devices in the default xml, but that did not resolve the issue.
So any help is welcome.
Thanks,
Eric

**Comment by tananaev** [comment]
Is the error still the same, including port number?

**Comment by stevenseh** [comment]
Yes

**Comment by tananaev** [comment]
That is not possible. You must be missing something.

**Comment by stevenseh** [comment]
Well unfortunately it is. I changed ports 5001..5050 to 5201..5250 and killed the prosees on port 5001. There is still a process on port 5002, which is now causing the issue, regardles of the chages in port numbers I made.
INFO|4536/0|Service traccar|17-07-17 19:31:43|java.lang.reflect.InvocationTargetException
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at java.lang.reflect.Method.invoke(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|4536/0|Service traccar|17-07-17 19:31:43|Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5002
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.traccar.TrackerServer.start(TrackerServer.java:117)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.traccar.ServerManager.start(ServerManager.java:81)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.traccar.Main.main(Main.java:38)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	... 6 more
INFO|4536/0|Service traccar|17-07-17 19:31:43|Caused by: java.net.BindException: Address already in use: bind
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.nio.ch.Net.bind0(Native Method)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO|4536/0|Service traccar|17-07-17 19:31:43|	at java.lang.Thread.run(Unknown Source)
INFO|wrapper|Service traccar|17-07-17 19:31:43|calling onStop
INFO|wrapper|Service traccar|17-07-17 19:31:43|Win service stop - timeout: 30000
INFO|wrapper|Service traccar|17-07-17 19:31:43|Win service wrapper.control -> stopping application
INFO|wrapper|Service traccar|17-07-17 19:31:43|Win service stop - after shutdown
INFO|wrapper|Service traccar|17-07-17 19:31:43|Win service stop - before notify
INFO|wrapper|Service traccar|17-07-17 19:31:43|Win service terminated

**Comment by tananaev** [comment]
If you change port from 5002 to something else, you shouldn't have any conflict with that port anymore.

You should not change port 5001 to 5050 because 5050 is already used by Traccar.

If you have so many conflicts, I would recommend to remove all the protocols that you don't need from `default.xml` config file.
