### ISSUE TITLE
server not sending mails

### ISSUE THREAD

**Issue by yanivsetton** [tananaev/traccar#3699]
Hi,
i can't send mails, check all possibles configurations
please see the logs that came from the container when trying to send mail from server
i also use mysql container if it change anything..
```
Exception in thread "Thread-12" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at org.traccar.model.ExtendedModel.getString(ExtendedModel.java:89)
        at org.traccar.notification.PropertiesProvider.getString(PropertiesProvider.java:39)
        at org.traccar.notification.NotificationMail.getProperties(NotificationMail.java:48)
        at org.traccar.notification.NotificationMail.sendMailSync(NotificationMail.java:92)
        at org.traccar.notification.NotificationMail$1.run(NotificationMail.java:134)
        at java.lang.Thread.run(Thread.java:748)
```

configuration from server side
```
Mail: SMTP Host | smtp.gmail.com
Mail: SMTP Port | 587
Mail: SMTP From | ***@gmail.com
Mail: SMTP Auth Enable | true
Mail: SMTP Username | ***@gmail.com
Mail: SMTP Password | ***
Mail: SMTP STARTTLS Enable | true
```
check that with ssl port 465 

please help

thanks

**Comment by tananaev** [comment]
Please don't duplicate your messages in future.

https://www.traccar.org/forums/topic/cant-send-mails/
