### ISSUE TITLE
Traccar on synology not started

### ISSUE THREAD

**Issue by aplanica** [tananaev/traccar#3713]
Hi
On my synology DS414 traccar not start :(
in wrapper log is errors:

`STATUS | wrapper  | 2018/01/14 12:54:12 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2018/01/14 12:54:12 | Java Service Wrapper Community Edition 32-bit 3.5.30
STATUS | wrapper  | 2018/01/14 12:54:12 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2018/01/14 12:54:12 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2018/01/14 12:54:12 |
STATUS | wrapper  | 2018/01/14 12:54:13 | Launching a JVM...
INFO   | jvm 1    | 2018/01/14 12:54:14 | WrapperManager: Initializing...
INFO   | jvm 1    | 2018/01/14 12:54:19 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp:
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to databa
se server. Attempted reconnect 3 times. Giving up.
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.initDatabase(DataManager.java:111)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.<init>(DataManager.java:66)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server
. Attempted reconnect 3 times. Giving up.
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2163)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2088)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:508)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       ... 12 more
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server
.
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       ... 26 more
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error: Caused by: java.net.ConnectException: Connection refused (Connection refused)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.PlainSocketImpl.socketConnect(Native Method)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at java.net.Socket.connect(Socket.java:589)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
INFO   | jvm 1    | 2018/01/14 12:54:28 | WrapperSimpleApp Error:       ... 28 more
STATUS | wrapper  | 2018/01/14 12:54:30 | <-- Wrapper Stopped
`

**Comment by tananaev** [comment]
Traccar is not able to connect to your database.
