### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by mgfoad** [tananaev/traccar#3794]
would you please help me, i couldn't start the traccar server process. here you are the log file,
```
WARNING|wrapper|Service traccar|18-03-05 02:17:59|YAJSW: yajsw-stable-12.11
WARNING|wrapper|Service traccar|18-03-05 02:17:59|OS   : Windows 10/10.0/amd64
WARNING|wrapper|Service traccar|18-03-05 02:17:59|JVM  : Oracle Corporation/1.8.0_161/C:\Program Files\Java\jre1.8.0_161/64
INFO|wrapper|Service traccar|18-03-05 02:17:59|start delay: 0
INFO|wrapper|Service traccar|18-03-05 02:17:59|started process with pid 2020
INFO|2020/0|Service traccar|18-03-05 02:18:00|[INFO] StandardFileSystemManager - Using "C:\Windows\TEMP\vfs_cache" as temporary files store.
INFO|2020/0|Service traccar|18-03-05 02:18:01|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|2020/0|Service traccar|18-03-05 02:18:01|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO|2020/0|Service traccar|18-03-05 02:18:01|INFO 3/5/18 2:18 AM: liquibase: Clearing database change log checksums
INFO|2020/0|Service traccar|18-03-05 02:18:02|INFO 3/5/18 2:18 AM: liquibase: Successfully acquired change log lock
INFO|2020/0|Service traccar|18-03-05 02:18:02|INFO 3/5/18 2:18 AM: liquibase: Successfully released change log lock
INFO|2020/0|Service traccar|18-03-05 02:18:02|INFO 3/5/18 2:18 AM: liquibase: Successfully acquired change log lock
INFO|2020/0|Service traccar|18-03-05 02:18:03|INFO 3/5/18 2:18 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|2020/0|Service traccar|18-03-05 02:18:03|INFO 3/5/18 2:18 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|2020/0|Service traccar|18-03-05 02:18:03|INFO 3/5/18 2:18 AM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Constraint "UK_USER_TOKEN" not found; SQL statement:
INFO|2020/0|Service traccar|18-03-05 02:18:03|ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token [90057-196] [Failed SQL: ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token]
INFO|2020/0|Service traccar|18-03-05 02:18:03|INFO 3/5/18 2:18 AM: liquibase: Successfully released change log lock
INFO|2020/0|Service traccar|18-03-05 02:18:03|[main] INFO org.eclipse.jetty.util.log - Logging initialized @3636ms
INFO|2020/0|Service traccar|18-03-05 02:18:04|java.lang.reflect.InvocationTargetException
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at java.lang.reflect.Method.invoke(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|2020/0|Service traccar|18-03-05 02:18:04|Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5040
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.traccar.TrackerServer.start(TrackerServer.java:117)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.traccar.ServerManager.start(ServerManager.java:81)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.traccar.Main.main(Main.java:38)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	... 6 more
INFO|2020/0|Service traccar|18-03-05 02:18:04|Caused by: java.net.BindException: Address already in use: bind
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.nio.ch.Net.bind0(Native Method)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.nio.ch.Net.bind(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO|2020/0|Service traccar|18-03-05 02:18:04|	at java.lang.Thread.run(Unknown Source)
INFO|wrapper|Service traccar|18-03-05 02:18:05|calling onStop
INFO|wrapper|Service traccar|18-03-05 02:18:05|Win service stop - timeout: 30000
INFO|wrapper|Service traccar|18-03-05 02:18:05|Win service wrapper.control -> stopping application
INFO|wrapper|Service traccar|18-03-05 02:18:05|Win service stop - after shutdown
INFO|wrapper|Service traccar|18-03-05 02:18:05|Win service stop - before notify
INFO|wrapper|Service traccar|18-03-05 02:18:05|Win service terminated
```

**Comment by tananaev** [comment]
You have a port conflict with other process. It has been discussed on forum countless number of times.
